### ISSUE TITLE
Improve Doc comments

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgrest-js#111]
This is a Hacktoberfest task! 
You can read more about Hacktoberfest [on our blog](https://supabase.io/blog/2020/09/11/supabase-hacktoberfest-2020) and see all tasks on our [Hacktoberfest Project Board](https://github.com/orgs/supabase/projects/5).

## Summary

We need help with checking and improving the inline comments for this library using [JSDoc](https://jsdoc.app/). 

## Details

If you've never see JSDoc before, it's the comment that go above functions. For example:

```js
/**
   * Creates a new user.
   * 
   * Some longer description can go here.
   * 
   * @param {object} credentials The user login details.
   * @param {string} credentials.email The user's email address.
   * @param {string} credentials.password The user's password.
   */
  async signUp(credentials: { email: string; password: string }) {
    // ...
  }
```

**Comment by fatmali** [comment]
Hi @kiwicopple is this available?

**Comment by awalias** [comment]
thanks for the interest @fatmali , assigning you now 👍

**Comment by fatmali** [comment]
Thanks @awalias , could you guide me on which specific files need to have jsdoc comments? I can see some inline comments in the files in the `src` directory with external links? What would the js doc comments look like for such files?

**Comment by awalias** [comment]
it looks like this one might actually already be complete, I couldn't find any methods missing JSDocs at the moment - will wait for @kiwicopple to confirm

**Comment by kiwicopple** [comment]
HI @fatmali , you could look into the Builder file: https://github.com/supabase/postgrest-js/blob/master/src/builder.ts

For example: 

```js
 /**
 * description
 */
interface PostgrestError {
   /**
   * description
   */
  message: string

   /**
   * description
   */
  details: string
}
```

and on the `class` and on the `constructor` :) 

If you do even a small one of the `interface PostgrestError`, I can merge it 👍
