### ISSUE TITLE
Ordering JSON column not working

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgrest-js#131]
# Bug report

## Describe the bug

This is failing 

```
const { data: products, error } = await supabase
        .from('products')
        .select('*')
        .order('metadata->index'
```

Caused by this: 

https://github.com/supabase/postgrest-js/blob/43b093d7eaab1c36b76b11cbcb1cfc2b3605c4a2/src/lib/PostgrestTransformBuilder.ts#L27

If we remove the quotes from the `"${column}"` then it works.

**Comment by kiwicopple** [comment]
@soedirgo - just need to get an understanding of the `"${column}"`. Is there a requirement for it to be wrapped in quotes?

**Comment by thorwebdev** [comment]
To give an example, this is my supabase-js query:

```js
const { data: products, error } = await supabase
        .from('products')
        .select('*, prices(*)')
        .eq('active', true)
        .order('metadata->index')
        .order('unit_amount', { foreignTable: 'prices' });
```

This is what postgrest-js currently generates:

https://jhomlobmvyuadfdnpnkb.supabase.co/rest/v1/products?select=*%2Cprices%28*%29&active=eq.true&order=%22metadata-%3Eindex%22.asc.nullslast&%22prices%22.order=%22unit_amount%22.asc.nullslast&apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYwNTA3MTUwNSwiZXhwIjoxOTIwNjQ3NTA1fQ.FZJkLOldXfPWN7Gtq7J4zFIh5cmnzSzBh_U3Jb0fjhY

Which errors with 

```json
{
  "hint": null,
  "details": null,
  "code": "42703", 
  "message": "column products.metadata->index does not exist"
}
```

when I remove the quotes from all order parts it works:

https://jhomlobmvyuadfdnpnkb.supabase.co/rest/v1/products?select=*%2Cprices%28*%29&active=eq.true&order=metadata-%3Eindex.asc.nullslast&%22prices%22.order=unit_amount.asc.nullslast&apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYwNTA3MTUwNSwiZXhwIjoxOTIwNjQ3NTA1fQ.FZJkLOldXfPWN7Gtq7J4zFIh5cmnzSzBh_U3Jb0fjhY

**Comment by soedirgo** [comment]
> Is there a requirement for it to be wrapped in quotes?

This was to anticipate column names like `player.name` which you'd need to wrap in quotes, but breaking JSONB columns makes this a nonstarter. Will push a fix soon 👍.

**Comment by soedirgo** [comment]
Also, I don't think postgrest-js supports ordering on multiple columns, doing multiple `order`s will ignore the previous ones. Will try to make this work as well.
