### ISSUE TITLE
Rename filters

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgrest-js#148]
Some of the filter names are very short. Names like `.sl()`, `.sr()`, `.adj()` can be hard to remember what to they do. I think it would lead to clearer and more declarative code if the function names were a bit longer.

Current list of filters: https://supabase.io/docs/client/using-filters

## Rename suggestions:

- `.cs()` -> `.contains()` or add a `json: true` option to `.in()`
- `.cd()` -> `.within()`
- `.sl()` -> `.rangeLt()` or add a `range` option to `.lt(column, value, {range: true})`
- `.sr()` -> `.rangeGt()` or add a `range` option to `.gt(column, value, {range: true})`
- `.nxl()` -> `rangeGte()` or add a `range` option to `.gte(column, value, {range: true})`
- `.nxr()` -> `rangeLte()` or add a `range` option to `.lte(column, value, {range: true})`
- `.adj()` -> `.adjacent()`
- `.ova()` -> `.within()`
- `.fts()` -> `.textSearch(column, search, {type: 'tsvector'})`
- `.plfts()` -> `.textSearch(column, search, {type: 'plainto'})`
- `.phfts()` -> `.textSearch(column, search, {type: 'phraseto'})`
- `.wfts()` -> `.textSearch(column, search, {type: 'websearch'})`

_Originally posted by @joshnuss in https://github.com/supabase/supabase/discussions/534_

**Comment by eunjae-lee** [comment]
maybe just aliases should be fine since it won't break anything.
