### ISSUE TITLE
Ordering nested tables doesn't work for more than 1 level

### ISSUE THREAD

**Issue by joshnuss** [supabase/postgrest-js#149]
# Bug report

`order()` only works if joined table is one level deep. 

## To Reproduce

Run a query with multiple levels of joins:

My schema: `boards` -> has many `lists` -> has many `cards`.
Each table has a `position` column.

```javascript
supabase
  .from('boards')
  .select('id, title, lists ( id, title, position, cards ( id, description, position ))') // 2-levels of nesting
  .order('position') // this works
  .order('position', {foreignTable: 'lists'}) // this works
  .order('position', {foreignTable: 'lists.cards'}) // this doesn't work
```

## Expected behavior

Sorting should work on any level of nesting.

# Research

PostgREST [does support this](https://github.com/PostgREST/postgrest/blob/cc54135bf0b1e635f2ff56c6899401c653b6281a/test/Feature/QuerySpec.hs#L661), the issue is due to quoting of the `foreignTable` param here: 

https://github.com/supabase/postgrest-js/blob/8cf6e0020a4a04f326fcaed704239db1dee9853d/src/lib/PostgrestTransformBuilder.ts#L48

When I remove the quoting locally, the sorting works correctly.

**Comment by kiwicopple** [comment]
@soedirgo was there any reason you added the quotes here?

**Comment by soedirgo** [comment]
Seems like a continuation of #131. Same reason for quoting: to handle special characters.

I think we can just assume that 95% of table/column names don't have special characters, and just let users quote the names manually. It's leaky, but should stop issues like this from happening.

Places to update: `order`, `limit`, `range`, `cleanFilterArray`.
