### ISSUE TITLE
"JSON Parse error: Unexpected EOF" in React Native

### ISSUE THREAD

**Issue by hey-hank** [supabase/postgrest-js#154]
# Bug report

## Describe the bug
Following the repro steps below with version 0.16.1, everything works and the response is parsed as expected.
(Version 0.18.0 gives me some error about not being able to resolve the module - likely unrelated to this)
Then version 0.18.1 as well as the most recent 0.24.2 gives me the following error:
```
JSON Parse error: Unexpected EOF
* [native code]:null in parse
- node_modules/react-native/node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
- node_modules/react-native/node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:14 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:30 in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
```

## To Reproduce

`expo init my-repro-app`
(I chose blank (Typescript))
`cd my-repro-app`
`npm install @supabase/postgrest-js`
Add the following code to `App.tsx`
```tsx
const supabaseRestUrl = '<supabase-url>' + '/rest/v1'
const supabaseKey = '<supabase-key>'
const client = new PostgrestClient(supabaseRestUrl, {
  headers: { apikey: supabaseKey },
  schema: 'public',
})

async function insertSomething() {
  try {
    const res = await client.from('cities').insert([{ name: 'Berlin' }])
    console.log(res)
  } catch (e) {
    console.error(e)
  }
}

insertSomething()
```
`npm start`, open the app in Expo on your phone and you should see the error. Happens on both ios and android.

After doing some poking around, I changed line 67 of `my-repro-app/node_modules/@supabase/postgrest-js/dist/main/lib/types.js`
from: `error = yield res.json();`
to: `error = yield JSON.parse(JSON.stringify(res));`
And that seemed to fix the issue?

## Expected behavior
Response should be parsed without error.

## System information

- OS: maxOS 11.1
- Version of supabase-js: 0.18.1 and 0.24.2
- Version of Node.js: 15.3.0

**Comment by kiwicopple** [comment]
Good catch @hey-hank, likely the error being returned isn't a JSON object:

https://github.com/supabase/postgrest-js/blob/eacc4f789551058bdf50bfe9aaabc4b435cd7d99/src/lib/types.ts#L108

We will need to put guards on it like we do here:

https://github.com/supabase/gotrue-js/blob/3501d62e4a8435a1bd749ca39cb01dc5e14efbfa/src/lib/fetch.ts#L15

**Comment by soedirgo** [comment]
Yet another victim to react-native's URL polyfill 😂 (see https://github.com/supabase/supabase/issues/353, https://github.com/facebook/react-native/pull/30188). Can you see if [this](https://github.com/facebook/react-native/issues/23922#issuecomment-648096619) fixes the issue?

> likely the error being returned isn't a JSON object

I don't think we need to do a check here. In the case of a non-2XX like above, PostgREST should return an error object along with 4/5XX status code. If it's a 4/5XX and the body isn't JSON, that might indicate another problem (as is the case here).

**Comment by hey-hank** [comment]
That worked! After `npm install react-native-url-polyfill` and adding to App.tsx: `import "react-native-url-polyfill/auto"`the error is no longer there and the response comes back correctly :)

**Comment by soedirgo** [comment]
Great to hear that! Closing this for now - let us know if you have other issues 😉
