### ISSUE TITLE
Consider using types instead of interfaces

### ISSUE THREAD

**Issue by inian** [supabase/postgrest-js#158]
Currently PostgrestError is [an interface](https://github.com/supabase/postgrest-js/blob/4c1b2278256095c952a99aad01ab7446f9598a1c/src/lib/types.ts#L8). 

I can't pass a PostgrestError into a function which the following signature` (obj: Record<string, unknown>): void; ` and I get an error saying 
```
Argument of type 'PostgrestError' is not assignable to parameter of type 'Record<string, unknown>'.
      Index signature is missing in type 'PostgrestError'.ts
```

This is due to a long open [typescript issue](https://github.com/microsoft/TypeScript/issues/15300) which looks like it is a working-as-intended issue. 

The [suggested workout](https://github.com/microsoft/TypeScript/issues/15300#issuecomment-436793742) is spread the error object before passing it into a function which is messy.

WDYT?

**Comment by soedirgo** [comment]
Idiomatic TypeScript [prefers interfaces](https://www.typescriptlang.org/docs/handbook/advanced-types.html#interfaces-vs-type-aliases) unless it's problematic, which in this case it is. The only thing we're missing is [merged declarations](https://stackoverflow.com/a/37233777), which is probably not needed for an error type, so +1
