### ISSUE TITLE
client.order only supports a single column

### ISSUE THREAD

**Issue by phamhieu** [supabase/postgrest-js#163]
# Bug report

## Describe the bug

Postgrest ordering support a list of columns and directions. [Link](https://postgrest.org/en/v7.0.0/api.html?highlight=order#ordering)
`/people?order=age.desc,height.asc`

However `postgrest-js` only support a single column ordering
```js
client.order('id', { ascending: false }).order('name', { ascending: false }) 
// this will result in &order=name.asc.nullslast
```

**Comment by inian** [comment]
This was just implemented yesterday https://github.com/supabase/postgrest-js/pull/162
Can you check with the latest version Hieu?

**Comment by phamhieu** [comment]
I this lib from `supabase-js`. Will wait for that to update with latest `postgrest-js`. Thanks @inian

**Comment by soedirgo** [comment]
I'll update supabase-js once I resolve https://github.com/supabase/postgrest-js/issues/148 and https://github.com/supabase/postgrest-js/issues/161 🙏
