### ISSUE TITLE
No function matches Levenshtein stored procedure

### ISSUE THREAD

**Issue by kylewelsby** [supabase/postgrest-js#168]
# Bug report

## Describe the bug

Working with Supabase and on a Nuxt.js project, so far things are going very well, very enjoyable and getting a new found love for SQL again. 

I've started getting to some interesting points of Supabase with stored procedures to perform fuzzysearches. 

I have a resemblance of a search query that joins a table creates a concatenated string to compare to a given string to calculate the `LEVENSHTEIN` distance for search results that return something useful for user. 

This procedure works well in the SQL explorer. (seen below)

I can't seem to get my Supabase.js to perform the query, instead, it returns the below error message. 

I have included as much information to help debug this. 

stored procedure 
```sql
CREATE OR REPLACE FUNCTION public.search_tracks(query text)
RETURNS TABLE(id text, artist text, title text, full_name text, distance int) AS $$
  SELECT tracks.id, artists.title AS artist, tracks.title, concat(artists.title, ' - ', tracks.title) AS full_name, LEVENSHTEIN(LOWER(CONCAT(artists.title, ' - ', tracks.title)), LOWER(query)) AS distance 
    FROM tracks 
  LEFT JOIN artists ON artists.id = tracks.artist
  ORDER BY distance ASC
  LIMIT 20;
$$ LANGUAGE SQL immutable;
```

```javascript
{
  error: {
    hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
    details: null,
    code: '42883',
    message: 'function levenshtein(text, text) does not exist'
  },
  data: null,
  count: null,
  status: 404,
  statusText: 'Not Found',
  body: null
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```javascript
const resp = await $supabase
  .rpc('search_tracks', { query: 'test' })
  .select('*')
```

## System information

- OS: `macos`
- Browser (if applies) `chrome`
- Version of supabase-js: 
  - `@supabase/postgrest-js@^0.26.1`
  - `@supabase/supabase-js@^1.3.4`
- Version of Node.js: `v14.16.0`

## Additional context

```sql
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch WITH SCHEMA extensions;
CREATE TABLE public.artists (
    id character varying NOT NULL,
    title character varying NOT NULL,
);
CREATE TABLE public.tracks (
    id character varying NOT NULL,
    title character varying NOT NULL,
    artist character varying NOT NULL,
);
INSERT INTO artists (id, title) VALUES ('art_1', 'Daft Punk');
INSERT INTO tracks (id, title, artist) VALUES ('trk_1', 'Harder Faster Stronger', 'art_1');
```

Run the procedure

```sql
SELECT search_tracks('Daft Punk - hard fast strong');
```

**Comment by steve-chavez** [comment]
Hey @kylewelsby,

To fix this, try the following:

- On the web UI. Go to `settings/api`(click on cog-> then API)
- On `EXTRA SEARCH PATH`. Add `public, extensions`. Then hit `Save`.

Let me know if that works.

**Comment by kylewelsby** [comment]
HI @steve-chavez, 

I added that and retried the request,  unfortunately, it did not work. 

Do I need to refresh authorization sessions or something for the changes to take hold?

More debugging if it helps. 

```bash
curl 'https://REDACTED.supabase.co/rest/v1/rpc/search_tracks' \
  -H 'authority: REDACTED.supabase.co' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"' \
  -H 'dnt: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'authorization: Bearer REDACTED' \
  -H 'content-type: application/json' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36' \
  -H 'content-profile: public' \
  -H 'apikey: REDACTED' \
  -H 'accept: */*' \
  -H 'origin: http://localhost:3000' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://localhost:3000/' \
  -H 'accept-language: en-GB,en;q=0.9,en-US;q=0.8' \
  --data-raw '{"query":"test"}' \
  --compressed
```


```json
{
  "hint":"No function matches the given name and argument types. You might need to add explicit type casts.",
  "details":null,
  "code":"42883",
  "message":"function levenshtein(text, text) does not exist"
}
```

**Comment by steve-chavez** [comment]
Another option is to add a search path to the function. Like this:

```sql
CREATE OR REPLACE FUNCTION public.search_tracks(query text)
RETURNS TABLE(id text, artist text, title text, full_name text, distance int) AS $$
  SELECT tracks.id, artists.title AS artist, tracks.title, concat(artists.title, ' - ', tracks.title) AS full_name, LEVENSHTEIN(LOWER(CONCAT(artists.title, ' - ', tracks.title)), LOWER(query)) AS distance 
    FROM tracks 
  LEFT JOIN artists ON artists.id = tracks.artist
  ORDER BY distance ASC
  LIMIT 20;
$$ LANGUAGE SQL immutable set search_path = 'public, extensions';
```

**Comment by kylewelsby** [comment]
Hey @steve-chavez 

Unfortunately even this hasn't worked, calling the function in the SQL tab works as expected. 
<img width="929" alt="Screenshot 2021-03-17 at 10 56 50" src="https://user-images.githubusercontent.com/110469/111456950-7d37cc00-870f-11eb-855e-4271c4a90356.png">


Just doesn't seem to work through Postrest-js / Supabase.js. 

```
function levenshtein(text, text) does not exist
```

Are there any more suggestions?

```diff
DROP FUNCTION search_tracks;
CREATE OR REPLACE FUNCTION public.search_tracks(query text)
RETURNS TABLE(id text, artist text, title text, full_name text, distance int) AS $$
  SELECT tracks.id, artists.title AS artist, tracks.title, concat(artists.title, ' - ', tracks.title) AS full_name, LEVENSHTEIN(LOWER(CONCAT(artists.title, ' - ', tracks.title)), LOWER(query)) AS distance 
    FROM tracks 
  LEFT JOIN artists ON artists.id = tracks.artist
  ORDER BY distance ASC
  LIMIT 20;
- $$ LANGUAGE SQL immutable set search_path = 'public, extensions';
+ $$ LANGUAGE SQL immutable SET search_path = public, extensions;
```

**Comment by steve-chavez** [comment]
@kylewelsby Try this one:

```diff
CREATE OR REPLACE FUNCTION public.search_tracks(query text)
RETURNS TABLE(id text, artist text, title text, full_name text, distance int) AS $$
  SELECT tracks.id, artists.title AS artist, tracks.title, concat(artists.title, ' - ', tracks.title) AS full_name,
- LEVENSHTEIN(LOWER(CONCAT(artists.title, ' - ', tracks.title)), LOWER(query)) AS distance 
+ extensions.LEVENSHTEIN(LOWER(CONCAT(artists.title, ' - ', tracks.title)), LOWER(query)) AS distance 
    FROM tracks 
  LEFT JOIN artists ON artists.id = tracks.artist
  ORDER BY distance ASC
  LIMIT 20;
$$ LANGUAGE SQL immutable;
```

(Namespace LEVENSHTEIN with `extensions.LEVENSHTEIN`)

**Comment by steve-chavez** [comment]
Depending on the role you use to make the call, you might also need to add a grant usage:

```sql
grant usage on schema extensions to anon;
grant usage on schema extensions to authenticated;
```

**Comment by kylewelsby** [comment]
Hey @steve-chavez 

Thanks for helping out on this one.

Namespacing the `LEVENSHTEIN` moved us closer with the following error message

```
{
  error: {
    hint: null,
    details: null,
    code: '42501',
    message: 'permission denied for schema extensions'
  },
  data: null,
  count: null,
  status: 403,
  statusText: 'Forbidden',
  body: null
}
```

Both grants for `anon` or `authenticated` did not work, however granting for `service_role` did.

```SQL
GRANT USAGE ON SCHEMA extensions TO service_role;
```

I'm learning a bunch about how Postgres via Supabase, Thank You. 🤗

My specific issue is resolved now, I'm not sure if there's something that could be done on the project to provide some feedback for those new to the workings to understand and resolve the issue themselves, or enabling the `extensions` role in a configuration somewhere on supabase.io. 

Perhaps an update like such.  

```diff
{
-  "hint":"No function matches the given name and argument types. You might need to add explicit type casts.",
+  "hint":"No function matches the given name and argument types. You might need to add explicit type casts. Extensions will need to be namespaced and permissions granted. See https://supabase.io/docs/client/rpc#with-extension for details.",

  "details":null,
  "code":"42883",
  "message":"function levenshtein(text, text) does not exist"
}
```

```diff
{
  error: {
-    hint: null,
+    hint: "Extensions will need to be namespaced and permissions granted. See https://supabase.io/docs/client/rpc#with-extension for details.",
    details: null,
    code: '42501',
    message: 'permission denied for schema extensions'
  },
  data: null,
  count: null,
  status: 403,
  statusText: 'Forbidden',
  body: null
}
```

But I guess it's beyond the scope of this project as its nested deep in [PostgREST/postgrest](https://github.com/PostgREST/postgrest/blob/cc54135bf0b1e635f2ff56c6899401c653b6281a/test/Feature/JsonOperatorSpec.hs#L66)

**Comment by steve-chavez** [comment]
@kylewelsby Cool! Glad to know it worked.

> But I guess it's beyond the scope of this project as its nested deep in PostgREST/postgrest

Yes, this one should be fixed in Supabase. We want extensions to be used the same on the SQL Editor and supabase-js. 

Two things that should be fixed:

- `EXTRA SEARCH PATH` on the UI is not working now. This should default to `public, extensions`. With this you wouldn't need to namespace `LEVENSHTEIN` on the function.
- `grant usage on schema extensions` should be added to the roles by default.

**Comment by dshukertjr** [comment]
For anyone running into this issue, I was able to resolve this by running [these SQL commands](https://github.com/supabase/postgrest-js/issues/168#issuecomment-801168181) in my SQL editor.

**Comment by soedirgo** [comment]
Am able to resolve the permission error with grants, so closing the issue.

```sql
create or replace function public.test_function() returns int as $$
  select extensions.levenshtein('a', 'b');
$$ language sql;
grant execute on function extensions.levenshtein(text, text) to anon, authenticated, service_role;
```
