### ISSUE TITLE
upsert array returning 50 records

### ISSUE THREAD

**Issue by thakkaryash94** [supabase/postgrest-js#171]
# Bug report

## Describe the bug

upsert with an array length of more than 50 is returning only 50 records of the array.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table with a field
2. Run below command
```sh
const array = [{field: value}]      // add object 100 times
supabaseClient.from<definitions['table']>('table').upsert([array], { onConflict: 'field' }).select('id')
```
3. All 100 records are inserted into the table but it will return an array with only 50 records
```sh
[{ id: UUID }]              // this array will contain only 50 records
```

## Expected behavior

It should return all the 100 records with selected fields

## System information

- OS: macOS
- Version of supabase-js: 1.7.6
- Version of Node.js: 14.15.5

**Comment by kiwicopple** [comment]
Hey @thakkaryash94 can I confirm if you have a [max-rows](https://postgrest.org/en/v7.0.0/configuration.html#max-rows) set on your PostgREST instance?

(if you're using Supabase, this is under Settings > API)

**Comment by thakkaryash94** [comment]
Oh, I knew it must somewhere in config, I tried to search on dashboard and docs but couldn't find out. 

Thank you and sorry for creating the issue. Is this somewhere documented? It's really important I believe.

**Comment by kiwicopple** [comment]
Looks like we're lacking some docs for this one. I'll add an item to my (long list) of docs updates!
