### ISSUE TITLE
[Feature request] Improve syntax for using typescript "from" function

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/postgrest-js#172]
# Feature request

First off, it's great that I can use TypeScript to statically type check everything. I think the syntax could be improved, though.

Right now, you need to add the definitions to every database operation:

```ts
supabase.from<definitions['table']>('table').select('*')
```

This works, but isn't optimal for a few reasons:

- Need to declare the type for each `from` call
- Need to declare the table name multiple times (prone to mistyping the table name)
- The input to `from` is not checked (e.g., you could time `from('tables')` for the above snippet and it would not fail linting)

But what if the definitions were added to the supabase client instead?

```ts
// lib file to create the client
import { createClient } from '@supabase/supabase-js'

export const supabase = createClient<definitions>(supabaseUrl, supabaseKey)

// file where you use the client
supabase.from('table').select('*')
```

Then, you could be confident in your static type checking:

- No need to duplicate the table name in the `from` function
- It's guaranteed that all database calls are type checked
- The `from` input could be type-checked (i.e., it's just the `keyof definitions`)
- Cleaner code syntax all around
- Added benefit that in VS Code, you get autocomplete on the table names, making the code more self-documenting

**Comment by baba43** [comment]
This is still open, right? 
Because I thought about exacly the same.

**Comment by soedirgo** [comment]
This is resolved in https://github.com/supabase/postgrest-js/pull/279. It's still a prerelease right now, but will be released as v2 in a few weeks.
