### ISSUE TITLE
Error 'All object keys must match'

### ISSUE THREAD

**Issue by peachp** [supabase/postgrest-js#173]
# Bug report

## Describe the bug
When trying to insert an array of objects, where in some objects the key `field2` is present, and in others isn't, the JS API client errors to: 'All object keys must match'. The `field2` is not mandatory.

```
const { data, error } = await supabase
  .from('mytable')
  .insert([
    {
      field1: 'something'     
    },
    {
      field1: 'something',
      field2: 'something'        
    }      
])
```

## Desired behavior
The JS client / Supabase should default the mismatching fields to `null` or whatever is translated to NULL in Postgres. (As workaround I set the fields to `null` and it looks OK in my case.)

**Comment by Polyterative** [comment]
I would like to know about this myself since I'm trying to upsert.
 
In my situation I can have references to the ids of the rows but  in the same operation I also need to add new rows of which I do not have an identifier.

![image](https://user-images.githubusercontent.com/16295552/115749950-ead2ba00-a397-11eb-8380-ac7877e82f08.png)
This returns
`{"message":"All object keys must match"}
`
summing up the upsert does not do what I expect that is to add new rows and update those already present in the same operation. 

this forces me to have to make two separate api calls for insert and update

**Comment by steve-chavez** [comment]
>  I also need to add new rows of which I do not have an identifier.

A workaround for making null identifiers work is to create a trigger that converts the null to the default id. Like:

```sql
-- Change items and its sequence according to your table
CREATE OR REPLACE FUNCTION items_null_id_is_default() RETURNS TRIGGER AS $$
BEGIN
  NEW.id = coalesce(NEW.id, nextval('items_id_seq'));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER items_null_id_is_default 
BEFORE INSERT ON items FOR EACH ROW EXECUTE PROCEDURE items_null_id_is_default();
```

Then you can avoid the `All object keys must match` error by adding a null id on the rows for which you don't have an identifier:

```js
[
    {
      id: null,
      name: 'a name'
    },
    {
      id: 123,
      name: 'another name'        
    }
]
```

(`upsert` should work then).

Once https://github.com/PostgREST/postgrest/issues/1567 is cleared out then the library will allow this out-of-the-box.

**Comment by JVariance** [comment]
> 
> 
> > I also need to add new rows of which I do not have an identifier.
> 
> A workaround for making null identifiers work is to create a trigger that converts the null to the default id. Like:
> 
> ```sql
> -- Change items and its sequence according to your table
> CREATE OR REPLACE FUNCTION items_null_id_is_default() RETURNS TRIGGER AS $$
> BEGIN
>   NEW.id = coalesce(NEW.id, nextval('items_id_seq'));
>   RETURN NEW;
> END;
> $$ LANGUAGE plpgsql;
> CREATE TRIGGER items_null_id_is_default 
> BEFORE INSERT ON items FOR EACH ROW EXECUTE PROCEDURE items_null_id_is_default();
> ```
> 
> Then you can avoid the `All object keys must match` error by adding a null id on the rows for which you don't have an identifier:
> 
> ```js
> [
>     {
>       id: null,
>       name: 'a name'
>     },
>     {
>       id: 123,
>       name: 'another name'        
>     }
> ]
> ```
> 
> (`upsert` should work then).
> 
> Once [PostgREST/postgrest#1567](https://github.com/PostgREST/postgrest/issues/1567) is cleared out then the library will allow this out-of-the-box.

Do I have to create the sequence ('items_id_seq') manually or is it automatically created by supabase?

**Comment by JVariance** [comment]
> 
> 
> > > I also need to add new rows of which I do not have an identifier.
> > 
> > 
> > A workaround for making null identifiers work is to create a trigger that converts the null to the default id. Like:
> > ```sql
> > -- Change items and its sequence according to your table
> > CREATE OR REPLACE FUNCTION items_null_id_is_default() RETURNS TRIGGER AS $$
> > BEGIN
> >   NEW.id = coalesce(NEW.id, nextval('items_id_seq'));
> >   RETURN NEW;
> > END;
> > $$ LANGUAGE plpgsql;
> > CREATE TRIGGER items_null_id_is_default 
> > BEFORE INSERT ON items FOR EACH ROW EXECUTE PROCEDURE items_null_id_is_default();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you can avoid the `All object keys must match` error by adding a null id on the rows for which you don't have an identifier:
> > ```js
> > [
> >     {
> >       id: null,
> >       name: 'a name'
> >     },
> >     {
> >       id: 123,
> >       name: 'another name'        
> >     }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (`upsert` should work then).
> > Once [PostgREST/postgrest#1567](https://github.com/PostgREST/postgrest/issues/1567) is cleared out then the library will allow this out-of-the-box.
> 
> Do I have to create the sequence ('items_id_seq') manually or is it automatically created by supabase?

I found the answer here: https://stackoverflow.com/a/10332015.
The 'items_id_seq' is automatically created on table 'items' for 'items.id'.

**Comment by CR1AT0RS** [comment]
I have this exact same issue.

**Comment by shopsideau** [comment]
> I would like to know about this myself since I'm trying to upsert.
> 
> In my situation I can have references to the ids of the rows but in the same operation I also need to add new rows of which I do not have an identifier.
> 
> ![image](https://user-images.githubusercontent.com/16295552/115749950-ead2ba00-a397-11eb-8380-ac7877e82f08.png)
> 
> This returns `{"message":"All object keys must match"}`
> 
> summing up the upsert does not do what I expect that is to add new rows and update those already in db in the same operation.
> 
> this forces me to have to make two separate api calls for insert and update

+1 for allowing this pattern

**Comment by UngererFabien** [comment]
It feels like it should at least allow the upsert with missmatching keys when a default value is provided for the missmatched keys in the table.

So that upsert like this is possible:
`{
      field1: 'something'
      field2: 'something'
    },
    {
      field1: 'something',
      field2: undefined // default value provided or null authorised on table.
 }`

**Comment by travisanderson** [comment]
+1 for this.  I mean, I thought that is what upsert is for.

I have multiple rows...if I add a new one, it doesn't have an ID yet...so, I would expect existing items get updated, while the new one, gets inserted.

**Comment by noeleom** [comment]
+1 for this as well. trigger only feels like a workaround and not expected behavior.

**Comment by ScarVite** [comment]
any update for this?

been quite for a while now.

**Comment by steve-chavez** [comment]
FYI, this is being worked at https://github.com/PostgREST/postgrest/pull/2672.
