### ISSUE TITLE
Fetch data as CSV instead of JSON

### ISSUE THREAD

**Issue by nstrelow** [supabase/postgrest-js#186]
I would like to download a table or certain rows of a table in CSV format instead of JSON.

Postgres has support for this here: https://postgrest.org/en/v7.0.0/api.html#response-format

So in theory, only the Accept header needs to be made configurable + disable the parsing after getting the response.

#### Use case
I am building research tools and researchers like their dataframes build upon CSV files.

**Comment by andreivreja** [comment]
> So in theory, only the Accept header needs to be made configurable + disable the parsing after getting the response.

An built in parser that converts to the same object format as it currently is would also be amazing for those of us who just want to use CSV for response size reasons. In my use case, the JSON overhead makes up for around 75% of the response size, which is pretty common when not storing large strings.

**Comment by nstrelow** [comment]
Awesome your PR!
Will probably do the same for postgrest-dart, which I am actually using.

I agree, lower size using csv is probably very great, the parsing could be a bit complicated though.

**Comment by soedirgo** [comment]
Closed in #187.
