### ISSUE TITLE
Add a `skipDuplicates` option to insert

### ISSUE THREAD

**Issue by steve-chavez** [supabase/postgrest-js#189]
Requested in https://github.com/supabase/supabase/discussions/1834. PostgREST can skip duplicates by using the `Prefer: resolution=ignore-duplicates` header as documented [here](https://postgrest.org/en/stable/api.html#upsert).

```js
const { data, error } = await supabase
  .from('cities')
  .insert(
    [
      { name: 'The Shire', country_id: 554 },
      { name: 'Rohan', country_id: 555 }
    ],
    { skipDuplicates: true })
```

The option could also be named `ignoreDuplicates`.

**Comment by soedirgo** [comment]
Should this not be on `upsert()` instead? Does `on_conflict` matter with `Prefer: resolution=ignore-duplicates`?

**Comment by steve-chavez** [comment]
> Does on_conflict matter with Prefer: resolution=ignore-duplicates?

Yes, it considers the `on_conflict` constraint for choosing what duplicate column to ignore.

> Should this not be on upsert() instead? 

Yeah, I think it can be included on `upsert` instead.
