### ISSUE TITLE
`count` always runs on the whole table

### ISSUE THREAD

**Issue by soedirgo** [supabase/postgrest-js#190]
# Bug report

## Describe the bug

The `count` field on the response always represents the whole table despite filtering etc. This is because it's retrieved from `Prefer: count={exact|estimated|planned}`. It should instead come from `Content-Range` without the prefer `count` parameter.

## To Reproduce

1. Run a `.from().select().limit(1)`
2. Check the `count` (it's not 0 or 1).

## Expected behavior

It should be 0 or 1.

## Additional context

For now we should just let `count` represent the right value—for [supabase-js v2](https://github.com/supabase/supabase-js/issues/170) we should use the `Prefer: count` parameter in a dedicated `count` call and maybe `rpc()`.

**Comment by dshukertjr** [comment]
I think a typical use case of count is for pagination, so it would make sense to respect filters like `match` or `eq`, but I wonder if `count` should respect modifiers like `limit` or `range`. 

When I tested it, count did respect filters, but ignored modifiers, which feels like the desired behavior!

**Comment by soedirgo** [comment]
Yup, I can't repro the issue anymore either. Thanks for looping back in!
