### ISSUE TITLE
Aborting requests

### ISSUE THREAD

**Issue by statianzo** [supabase/postgrest-js#200]
# Feature request

## Is your feature request related to a problem? Please describe.

After the migration from Superagent to cross-fetch there doesn't seem to be a way to abort a request.
Consider this usage within React:

```ts
useEffect(() => {
  client
    .from("users")
    .select()
    .eq("id", userId)
    .then(({data}) => setUser(data[0]))

  return () => {
    // Stop in-flight request?
  }
}, [userId]);
```

## Describe the solution you'd like

Given postgrest-js is built on `cross-fetch` now, support AbortSignal.

```ts
useEffect(() => {
  const controller = new AbortController;
  client
    .from("users")
    .select()
    .eq("id", userId)
    .signal(controller.signal)
    .then(({data}) => setUser(data[0]));

  return () => {
    controller.abort();
  }
}, [userId]);
```

## Describe alternatives you've considered

This could be more generic to support other fetch options instead of strictly signal.

## Additional context

I'd be fine implementing this as a PR. Just need to know what direction the maintainers would prefer.

**Comment by soedirgo** [comment]
+1 for the feature, I'm not sure if we want to expose fetch options as we don't want to leak which HTTP client we're using under the hood, but we likely aren't moving away from fetch anytime soon so this one feature seems OK.

I'll have to look at how this can be implemented in clients for other languages, though it's no problem if it's JS-only.

**Comment by kyrelldixon** [comment]
Is this still being considered? I'd like users to be able to abort file uploads and haven't found a good alternative.

**Comment by soedirgo** [comment]
My bad, got sidetracked on this - will get back to it this weekend.

**Comment by inian** [comment]
storage-js [supports this](https://github.com/supabase/storage-js/blob/f650e1a504bd6137bd94880e37c1675c5eb996b7/src/lib/fetch.ts#L11) via AbortSignals, but is not yet documented. We can use the same mechanism for the other services too
