### ISSUE TITLE
`timestamptz` cols should be returned as `Date`s

### ISSUE THREAD

**Issue by nicholaschiang** [supabase/postgrest-js#201]
# Bug report

## Describe the bug

`Date` objects stored in PostgreSQL `timestamptz` columns are returned as ISO strings instead of `Date` objects when fetched using the Supabase JavaScript SDK.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a `timestamptz` column, like so:

```pgsql
create table users (
  created timestamptz not null,
  updated timestamptz not null
);
```
2. Create a new record using `Date` objects, like so:

```typescript
await supabase.from<User>('users').insert({
  created: new Date(),
  updated: new Date() 
});
```
3. Fetch that record:

```typescript
const { data } = await supabase.from<User>('users').select();
console.log(typeof data[0].created); // Logs "string" instead of "object"
console.log(data[0].created instanceof Date); // Logs "false" instead of "true"
```
4. See error.

## Expected behavior

Fields stored as `timestamptz` using `Date` objects should be returned by the Supabase JavaScript SDK as `Date`s instead of ISO strings.

## Additional context

Chatted with @burggraf about this on the Supabase Discord server earlier today.

**Comment by soedirgo** [comment]
Discord thread: https://discord.com/channels/839993398554656828/843999948717555735/871833245057155123

The reason `timestamptz` columns are returned as strings is because there is no `Date` type in JSON, and PostgREST responses are in JSON (or CSV, if you specify it).

@steve-chavez any input on this?

**Comment by burggraf** [comment]
Ah, that makes total sense.  `Postgrest` returns `JSON`!

**Comment by nicholaschiang** [comment]
@soedirgo @burggraf yup, I realized that. I was just thinking that because the `supabase-js` wrapper around Postgrest accepts `Date`s during `insert` and `update`, it should probably wrap around `Date`s during `select` requests (e.g. just have some regex to test whether or not a string is a date ISO string and, if it is, wrap it).

Or, an alternative solution, is to prevent users from passing `Date` objects to `insert` and `update` requests and force them to serialize it to a date string themselves (i.e. only allow JSON data types to be passed to the `insert` and `update` methods). That way, they'll realize that what they're getting back from `select` isn't going to be a `Date` but rather a JSON-serialized ISO string. What you pass into `insert` should be exactly what you get back from `select`.

**Comment by soedirgo** [comment]
postgrest-js accepts `Date` in `insert`/`update` only as a consequence of implicit type cast (`JSON.stringify`) - I imagine PostgREST clients for other languages without implicit type casting (e.g. postgrest-rs) force dates to be strings.

If you want to compare `insert`d/`update`d data with something from `select`, there's a solution: by default `insert`/`update` returns the inserted/updated data on success (see [here](https://supabase.io/docs/reference/javascript/insert#notes)). You can then compare it with the result from a `select`.

**Comment by steve-chavez** [comment]
> @steve-chavez any input on this?

Hm, perhaps the way forward for these conversions is to query the PostgREST's OpenAPI output in `postgrest-js` and refine the types?

There's also the case of [bigints being truncated in JS](https://github.com/PostgREST/postgrest/issues/498).

**Comment by burggraf** [comment]
I personally don't have a problem returning everything as a string, as long as I know what the types are supposed to be.  I'd rather have a bigint as a string that's accurate than have a truncated numeric value.

**Comment by soedirgo** [comment]
> Hm, perhaps the way forward for these conversions is to query the PostgREST's OpenAPI output in postgrest-js and refine the types?

That means we need 2 requests to do an insert/update - write throughput may not be as important as read throughput in most cases but I'd like to avoid that if possible.

I've given it some thought and decided to close this issue. I think lossy conversion is a dealbreaker - there's the `bigint` being truncated, but Postgres timestamps are *also* truncated since they have a resolution of 1 microsecond ([ref](https://www.postgresql.org/docs/current/datatype-datetime.html)).

Some other issues with this:
- maintenance burden of mapping of types & parsing logic
- having to unparse after parsing if you *do* want them to be strings

**Comment by steve-chavez** [comment]
> That means we need 2 requests to do an insert/update 

Here I was thinking more about doing one request when postgrest-js is initialized(to get OpenAPI).

Agree nonetheless, parsing it's a lot of work for now.

**Comment by cemo** [comment]
Any workaround for this?
