### ISSUE TITLE
Authentication sequence support

### ISSUE THREAD

**Issue by subhendukundu** [supabase/postgrest-js#203]
I was just wondering what is your take on Authentication sequence with postgrest-js?
With the current setup, is it possible to add it? or how can we achieve it?

I do see somecode in https://github.com/supabase/postgrest-js/blob/791dc09c92dfcb5a8dd064a1e02ac554a1ad0127/src/PostgrestClient.ts#L31 How can we use it?

context: https://postgrest.org/en/stable/auth.html

**Comment by steve-chavez** [comment]
Hey @subhendukundu,

[gotrue](https://github.com/supabase/gotrue/) is the component that produces the JWTs. `postgrest-js` just passes those(through the Authorization header) to the PostgREST server.

**Comment by kiwicopple** [comment]
> How can we use it?

to use this you would do something like:

```js
const { data, error } = postgrest
  .auth('VALID_JWT_TOKEN')
  .from('table_name')
  .select()
```

This will set the `Authorization` header (which is needed if you have set up PostgREST with the recommended approach here: https://postgrest.org/en/v7.0.0/auth.html

I'll close this one for now, but feel free to comment again if I misunderstood anything and I'll reopen 👍
