### ISSUE TITLE
Composite type filtering

### ISSUE THREAD

**Issue by soedirgo** [supabase/postgrest-js#207]
# Feature request

## Is your feature request related to a problem? Please describe.

Want to filter on composite type fields: https://github.com/supabase/supabase/discussions/2825

## Describe the solution you'd like

Wait for https://github.com/PostgREST/postgrest/issues/1543

## Describe alternatives you've considered

Workaround is to use a computed column.

**Comment by steve-chavez** [comment]
Implemented in https://github.com/PostgREST/postgrest/pull/2145.

Works the same as json with arrow operators:

```js
final response = await client
          .from('on_hand')
          .select()
          .filter("item->supplier_id", "eq", 1)
          .execute();
```

(Took the example from https://github.com/supabase/supabase/discussions/2825#discussion-3516077)
