### ISSUE TITLE
URLSearchParamSet in react-native not implemented error

### ISSUE THREAD

**Issue by theking465** [supabase/postgrest-js#221]
# Bug report

## Describe the bug

When performing a select query on a supabase database in an expo reactnative project, it calls the URL module from React-Native which isn't implemented.

## To Reproduce

Setup an expo project and add a simple select query. Run the project on Android.

## Expected behavior

Query is executed normally.

## Screenshots

![afbeelding](https://user-images.githubusercontent.com/9497296/140503068-05f0ca19-681c-444f-9d40-be4d2a83c589.png)

## System information

- OS: Windows WSL
- Version of supabase-js: 1.25.2
- Version of Node.js: v14.17

## Additional context

When googling I stumbled upon [this blog post](https://justinnoel.dev/2020/12/08/react-native-urlsearchparams-error-not-implemented/) which provides a workaround, but would be great if it got supported out of the box.

**Comment by soedirgo** [comment]
Looks similar to https://github.com/supabase/supabase/issues/353. The URL API exists on the browser, web workers, and Node.js, so the workaround is necessary for now until RN fixes it.
