### ISSUE TITLE
Cloudflare workers issues with cross-fetch (xmlhttprequest is not defined)

### ISSUE THREAD

**Issue by bkniffler** [supabase/postgrest-js#227]
This library uses cross-fetch, which makes running in Cloudflare workers impossible. 

Reference:
https://community.cloudflare.com/t/xmlhttprequest-is-not-defined/133866/4

Solution: 
Not using cross-fetch and let users polyfill via node-fetch/cross-fetch/isomorphic-fetch themselves. Obviously this will be super duper breaking. Not sure if there is any other way though.

**Comment by bnjmnt4n** [comment]
See https://github.com/supabase/supabase-js/pull/297 and https://github.com/supabase/postgrest-js/pull/222. Passing a custom `fetch` looks like it should be fully supported without bugs in supabase-js `0.28.1`.

**Comment by bkniffler** [comment]
Oh wow, great, thanks @bnjmnt4n. Just found https://github.com/lquixada/cross-fetch/issues/69 by coincidence and the username @kiwicopple seemed familiar :) 

I'll try the suggested solution and close this issue.

**Comment by soedirgo** [comment]
This should be resolved now afaik. Custom fetch is not needed - the lib now uses the global fetch if available, and otherwise falls back to cross-fetch (previously it always uses cross-fetch, which caused issues).
