### ISSUE TITLE
Foreign Key ambiguity on views

### ISSUE THREAD

**Issue by roker15** [supabase/postgrest-js#229]
I see a ciritical issue in making query with supabase is **`ambiguity`** when i have to refer foreign kyes. Even if you don't touch your current tables and Just create a **`view`**. It might break all your api call in your application. Never faced this kind of problem when was using hibernate in java. What u people doing about this. This is i think most critical thing for u guys. Just one change in database and everything is borken.

**Comment by steve-chavez** [comment]
Moving to postgrest-js because it seems related to https://postgrest.org/en/v9.0/api.html#embedding-disambiguation.

> Even if you don't touch your current tables and Just create a view.

Do you have a reproducible example(DDL) we can try?

**Comment by steve-chavez** [comment]
Relating this to https://github.com/supabase/supabase/discussions/6274#discussioncomment-2517906

**Comment by steve-chavez** [comment]
This was solved in https://github.com/PostgREST/postgrest/issues/2277. New views won't break previous requests.
