### ISSUE TITLE
!inner join not working: "Could not find a relationship between TABLE1 and TABLE2 in the schema cache"

### ISSUE THREAD

**Issue by mgm1313** [supabase/postgrest-js#231]
I've got exactly the same issue as described in the original post, but different from https://github.com/supabase/supabase/issues/4170#issuecomment-983084077 I can confirm I'm already on PostgREST 9:
```json
"info": {
    "title": "PostgREST API",
    "description": "This is a dynamic API generated by PostgREST",
    "version": "9.0.0 (c9f017c)"
  },
```

My query is: `https://__.supabase.co/rest/v1/course?select=age_category!inner(id)`

The error is:
```json
  "error": {
    "message": "Could not find a relationship between course and age_category in the schema cache",
    "hint": "If a new foreign key between these entities was created in the database, try reloading the schema cache."
  },
```

The same query, but without the explicit inner join does work as expected: `https://__.supabase.co/rest/v1/course?select=age_category(id)`

Running the code suggested in https://github.com/supabase/supabase/discussions/2579#discussioncomment-1060046 returned
```mysql
SELECT
    tc.table_schema, 
    tc.constraint_name, 
    tc.table_name, 
    kcu.column_name, 
    ccu.table_schema AS foreign_table_schema,
    ccu.table_name AS foreign_table_name,
    ccu.column_name AS foreign_column_name 
FROM 
    information_schema.table_constraints AS tc 
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name
      AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name
      AND ccu.table_schema = tc.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_name IN ('course', 'age_category');
```
```markdown
| table_schema | constraint_name             | table_name   | column_name     | foreign_table_schema | foreign_table_name | foreign_column_name |
| ------------ | --------------------------- | ------------ | --------------- | -------------------- | ------------------ | ------------------- |
| public       | fk_ageCategory              | course       | age_category_id | public               | age_category       | id                  |
```

I also restarted my Supabase-server from the dashboard, as well as ran `NOTIFY ddl_command_end;` inside the SQL editor.  

_Originally posted by @mgm1313 in https://github.com/supabase/supabase/issues/4170#issuecomment-988934320_

**Comment by steve-chavez** [comment]
Closing this one until further feedback is provided.

**Comment by lazyprogrammerP** [comment]
@steve-chavez I experienced the same error. I am trying to `inner join` two tables in my schema and it says `{
  hint: If a new foreign key between these entities was cr… in the database, try reloading the schema cache.,
  message: Could not find a relationship between transsecurity and category in the schema cache
}`

My code:

`const { data, error } = await client
    .from('transsecurity')
    .select('*, category!inner(*)')`

Can you please help me out on this?

**Comment by steve-chavez** [comment]
@lazyprogrammerP Is there a foreign key between transsecurity and category? Can you share the tables' definitions?
