### ISSUE TITLE
ESLint rule to avoid using `update` without filters

### ISSUE THREAD

**Issue by clouedoc** [supabase/postgrest-js#234]
# Feature request

## Problem

Sometimes, I forget to use filters with the `.update()` method.
By forgetting filters with `update()`, I destroyed the production database multiple times.
🙂 

## Solution

I'd like an ESLint rule that warns me when I forget to combine `.update()` with a filter (`.match()`, `.eq()`, etc)

## Alternatives

I don't know any alternative that would work. I think that ESLint is the proper tool for the job.

**Comment by steve-chavez** [comment]
Do you know you can prevent this at the database level with the [safeupdate](https://github.com/eradman/pg-safeupdate) extension?

You can enable it by doing:

```sql
ALTER DATABASE postgres SET session_preload_libraries = 'safeupdate';
```

The whenever trying to UPDATE without a a filter you'll get an error like

```
UPDATE requires a WHERE clause
```

**Comment by clouedoc** [comment]
@steve-chavez I didn't know it was possible; thank you for the hint.
I'll let this feature request open if it interests you, but you can consider my issue as fixed.

**Comment by soedirgo** [comment]
Note: do a `SHOW session_preload_libraries` first in case there are existing entries. On the hosted db we have `supautils` so I'd do
```sql
ALTER DATABASE postgres SET session_preload_libraries = 'supautils,safeupdate';
```

**Comment by clouedoc** [comment]
@soedirgo too late, I've overwritten the value 😬

Thanks for the heads up, I'll look at the next DB backup's diff to see if there was existing values.
