### ISSUE TITLE
 Chore: update Github description to supabase.com

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/postgrest-js#236]
# Chore

## Describe the chore

update Github description  from [supabase.io](https://supabase.com) to [supabase.com](https://supabase.com)

<img width="1392" alt="Screen Shot 2021-12-16 at 3 22 00 PM" src="https://user-images.githubusercontent.com/70828596/146443821-141267ee-16f3-4ca3-a9d5-105a87690d36.png">

**Comment by soedirgo** [comment]
Updated 👍
