### ISSUE TITLE
Ability to order by multiple columns

### ISSUE THREAD

**Issue by pangolingo** [supabase/postgrest-js#249]
# Feature request

## Is your feature request related to a problem? Please describe.

I don't see a way to order by multiple columns. Here's what I would do in SQL:
```
SELECT
	first_name,
	last_name
FROM
	customer
ORDER BY
	first_name ASC,
	last_name DESC;
```

## Describe the solution you'd like

I'd like the `order()` method to accept multiple columns. Here's an idea:

```
const { data, error } = await supabase
  .from('customer')
  .select('first_name', 'last_name')
  .order([
    { column: 'first_name', ascending: true },
    { column: 'last_name', ascending: false },
  ])
```

## Describe alternatives you've considered

I tried multiple `.order` methods and this didn't appear to work (maybe I screwed up the logic?)

```
const { data, error } = await supabase
  .from('customer')
  .select('first_name', 'last_name')
  .order('first_name', { ascending: true })
  .order('last_name, { ascending: false });
```

**Comment by steve-chavez** [comment]
> I tried multiple .order methods and this didn't appear to work

Hm, that should work, it's tested here:

https://github.com/supabase/postgrest-js/blob/5f47e84e917448d792c89e5be29c2f643c2a82ab/test/transforms.ts#L12-L19

Can you double check?

**Comment by jimmythigpen** [comment]
Related to this issue - I'm unable to sort by two dates, `updated_at` and `created_at`. What I expect to see is results ordered by `updated_at` if not null, otherwise `created_at`. What I'm seeing is two groups of sorted results based on `updated_at` and `created_at`. 

This is what I'm doing:
`.select().order('updated_at', { ascending: false })
    .order('created_at', { ascending: false });`

I've played around with the order and using `nullsFirst` but can't seem to get it right.

**Comment by nasiscoe** [comment]
Bump - ordering by multiple columns isn't working for me either. That test could be passing by coincidence?

**Comment by steve-chavez** [comment]
@nasiscoe Could you send me your project ref plus a sample query to steve@supabase.io so I can reproduce?

**Comment by spyl94** [comment]
I can confirm that multiple order by has been implemented in https://github.com/supabase/postgrest-js/pull/162 and is working great for me 👍 

You can check that the HTTP requests sent by supabase look like this : https://postgrest.org/en/stable/api.html?highlight=order#ordering

**Comment by steve-chavez** [comment]
@spyl94 Cool! Thanks for confirming.

To close this one I think we'd need an additional example("ordering multiple columns") here: https://supabase.com/docs/reference/javascript/order#examples

**Comment by spyl94** [comment]
I just added some documentation so we can probably close the issue !

**Comment by fightingcat** [comment]
> Related to this issue - I'm unable to sort by two dates, `updated_at` and `created_at`. What I expect to see is results ordered by `updated_at` if not null, otherwise `created_at`. What I'm seeing is two groups of sorted results based on `updated_at` and `created_at`.
> 
> This is what I'm doing: `.select().order('updated_at', { ascending: false }) .order('created_at', { ascending: false });`
> 
> I've played around with the order and using `nullsFirst` but can't seem to get it right.

Same problem :(
