### ISSUE TITLE
How to reload schema cache?

### ISSUE THREAD

**Issue by ryan-eiv** [supabase/postgrest-js#251]
# Bug report

## Describe the bug

Cannot call RPC with input variables

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create an RPC in Supabase UI:
```
CREATE OR REPLACE FUNCTION test_return_one(
  inputVariable text
)
    RETURNS int
    LANGUAGE 'plpgsql'
AS $$
begin
  return 1;
end
$$;
```
2. Test that it works in Supabase UI:
```
select * from test_return_one('hello');
```
(it works)

3. Call RPC from supabase.js
```
const { error, data } = await supabase
    .rpc('test_return_one', { inputVariable: 'hello' })
    .select();
console.log(error, data);
```
This errors out.

4. This is the error:
```
{
  error: {
    message: 'Could not find the public.test_return_one(inputVariable) function or the public.test_return_one function with a single unnamed json or jsonb parameter in the schema cache',
    hint: 'If a new function was created in the database with this name and parameters, try reloading the schema cache.'
  },
  data: null,
  count: null,
  status: 404,
  statusText: 'Not Found',
  body: null
}
```

5. I restarted local npm server and tried step 3 again with the same results.

note: this does work when you create a function without any variables.

## Expected behavior

I expect it to return the same data as the data seen in the Supabase UI.

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase-js: 1.29.4
- Version of Node.js: 12.17.0

**Comment by steve-chavez** [comment]
Add double quotes to "inputVariable" like:

```sql
CREATE OR REPLACE FUNCTION test_return_one(
  "inputVariable" text
)
```

By default PostgreSQL is case-insensitive so the parameter is being defined as "inputvariable" while the rpc snippet doesn't use this form.

**Comment by ryan-eiv** [comment]
That helped. Thank you!

**Comment by sean-gribben** [comment]
That may have helped, but the issue still _definitely_ exists that functions are not being found despite being explicitly defined. [See here](https://github.com/orgs/supabase/discussions/6461). It seems if you define a function inside the query editor rather than explicitly through the UI in supabase it doesn't create an endpoint for it.

So far only solution I've found for this is waiting.

The biggest issue with researching this issue is everyone who posts can't read and has just made a syntax error. The few who actually get the syntax right get buried so it's a massive pain to find any resources

**Comment by johnlarkin1** [comment]
@sean-gribben I think you are correct. 

For example, I'm seeing it on this call: 

```python
response = self.client.table("newsletters").insert(newsletter_dict).execute()
```

And I don't see any reason why after adding my foreign key, i'd be seeing this fail all of a sudden unless it's some underlying postgres / supabase issue.

**Comment by soedirgo** [comment]
Thanks @sean-gribben, I've changed the title to reflect the OP's issue. To answer the original title, [this](https://docs.postgrest.org/en/v12/references/schema_cache.html#schema-cache-reloading-with-notify) is how you can reload PostgREST's schema cache:

```
NOTIFY pgrst, 'reload schema'
```
