### ISSUE TITLE
Adding the ONLY keyword to the JS API

### ISSUE THREAD

**Issue by Teio07** [supabase/postgrest-js#252]
### Discussed in https://github.com/supabase/supabase/discussions/5927

<div type='discussions-op-text'>

<sup>Originally posted by **Teio07** March 15, 2022</sup>
Hi,
I'm considering handling deletion using partitions (to separate deleted records from non deleted records) as described in this post : 
https://stackoverflow.com/questions/506432/cascading-soft-delete

But once implemented, if I want to be able to select records (only non-deleted ones) I have to SELECT like this with Postgresql :
```
SELECT name, altitude
    FROM ONLY cities
    WHERE altitude > 500;
```
ref. : https://www.postgresql.org/docs/9.1/ddl-inherit.html#:~:text=Here%20the%20ONLY%20keyword%20indicates,DELETE%20%E2%80%94%20support%20the%20ONLY%20keyword.

Is such a call possible using supabase with react ?
How would that translate ?

Thanks in advance !</div>

**Comment by soedirgo** [comment]
Sorry for the very late response. AFAIK we don't do this on PostgREST - @steve-chavez can you confirm?

**Comment by steve-chavez** [comment]
Yes, not yet available on PostgREST

**Comment by steve-chavez** [comment]
@soedirgo Seeing that https://github.com/supabase/postgrest-js/issues/339 was closed. Perhaps all issues with the [postgrest-patch-needed](https://github.com/supabase/postgrest-js/issues?q=is%3Aissue+is%3Aopen+label%3Apostgrest-patch-needed) tag should be closed?

**Comment by soedirgo** [comment]
Hmm, I guess a rule of thumb is to close unless a feature is approved to be implemented upstream. In both of these cases though there's no associated PostgREST feature request.
