### ISSUE TITLE
Escape special characters in column names

### ISSUE THREAD

**Issue by anand2312** [supabase/postgrest-js#262]
# Bug report
While working on https://github.com/supabase-community/postgrest-py/pull/108 I found out that postgrest-js does not escape special characters in column names.

## Describe the bug
Columns that have PostgREST special characters `.,:()` should be escaped by surrounding in double quote `"`; this is not done and results in an API error.

## To Reproduce
```js
    const res = await client
        .from("test")
        .select("*")
        .eq(':col.name', 1);
    console.log(res);
```
results in error:
```json
{
  error: {
    message: '"failed to parse tree path (:col.name)" (line 1, column 1)',
    details: 'unexpected ":" expecting field name (* or [a..z0..9_])'
  },
  data: null,
  count: null,
  status: 400,
  statusText: 'Bad Request',
  body: null
}
```
Wrapping `:col.name` in double quotes before passing it to `.eq` works as expected.

**Comment by soedirgo** [comment]
This prohibits the use of foreign table filters: https://supabase.com/docs/reference/javascript/filter#filter-embedded-resources.

Currently you need to escape column names manually, but eventually we'd like to move away from stringly-typed params - ideally you wouldn't need to escape anything.
