### ISSUE TITLE
Cannot query foreign tables when table has a self-referential foreign key

### ISSUE THREAD

**Issue by phulengo** [supabase/postgrest-js#263]
# Bug report

## Describe the bug

I have a table named `Comments` that is directly related to table `Ideas`. I want to get/query all comments that have `comments.idea_id` = `ideas.ideas_id`.
![image](https://user-images.githubusercontent.com/30664920/161985256-06dd42ea-3b20-40e1-9d7c-47fbec4cbf79.png)

Below is my code snippet:
````typescript
export const getIdeasListByCategoryId = async (category_id: string, limit?: number) => {
	const noLimit = 99999;
	const { data, error } = await supabase
		.from('ideas')
		.select('*, comments(idea_id)')
		.match({ category_id: category_id })
		.limit(limit || noLimit);
	return { data, error };
};
````
After a long time of wondering why my code didn't work (data always return `null`) while the other tables (without self-referential records) did correctly. Then I tried to delete and re-created the `Comments` table many times and I realized that my code only works if it doesn't have the self-referential record (`parent_comment_id`).
![image](https://user-images.githubusercontent.com/30664920/161985893-aa171374-7c2f-4738-9d86-412d0c8fcbae.png)

Thus, if anyone has experienced my situation, please give me some advice. Thank you!
 
## To Reproduce

1. Create two tables with one has a self-referential record
2. Make a foreign table query
3. See error (always return `null`)

## Expected behavior

Successfully get all data from foreign tables.

## Screenshots

Mentioned above.

## System information

- OS: macOS Monterey 12.2.1
- Browser: Chrome
- Version of supabase-js: 1.30.7
- Version of Node.js: 16.7.0

## Additional context

None.

**Comment by steve-chavez** [comment]
> After a long time of wondering why my code didn't work (data always return null)

Did you caught the error message in that case? It always has more information in the `details` and `hint` fields.

**Comment by phulengo** [comment]
> > After a long time of wondering why my code didn't work (data always return null)
> 
> Did you caught the error message in that case? It always has more information in the `details` and `hint` fields.
> 
> It could be that more than one way to join `ideas` with `comments` was detected, in this case you needed to add a hint to `comments(idea_id)`. The error message clarifies that.

Sorry for my negligence, I only checked the `data` variable but the `error` one.
![image](https://user-images.githubusercontent.com/30664920/162279735-faec6a27-5b8f-46f0-b9ed-32ad9bcdf58f.png)
After replacing `comments(idea_id)` with `comments!comments_idea_id_fkey(*)` as `hint` described, the problem was solved although it's a little weird to me...

Btw, I found another way to achieve this by creating a Postgres function on the database server and calling it using `.rpc()`. Many thanks for your advice!

**Comment by steve-chavez** [comment]
No problem! 

> comments!comments_idea_id_fkey(*) as hint described, the problem was solved although it's a little weird to me...

Yeah, you can actually rename foreign keys so instead of `comments_idea_id_fkey` you can use a more friendlier name. The `rpc` route is good though.

Seeing the error message, I think the problem is that we're too liberal in detecting a many-to-many relationship, this can definitely be improved.

Linking to https://github.com/PostgREST/postgrest/issues/2070#issuecomment-996274638 - will revise this.
