### ISSUE TITLE
quirky .range() during pagination

### ISSUE THREAD

**Issue by madleo-dk** [supabase/postgrest-js#268]
# Bug report

## Describe the bug
When paginating using `range`, specifically at the last page, a duplicate item would be added in place of the correct item.
The workaround is to delete both items (duplicate item and correct item) from the dashboard, and re-enter in those items.

## To Reproduce

This may be a one-off cache related issue, I can't be certain, but i can't reproduce.
Feel free to close the issue, I simply wanted to bring it to the devs + community's attention in case someone runs into it.

**Comment by steve-chavez** [comment]
Is this related to the supabase-js range functions - like [rangeLt](https://supabase.com/docs/reference/javascript/rangelt)?

**Comment by steve-chavez** [comment]
>  specifically at the last page, a duplicate item would be added in place of the correct item

@madleo-dk The above sounds exactly like [PostgreSQL docs on inclusivity for ranges](https://www.postgresql.org/docs/current/rangetypes.html#RANGETYPES-INCLUSIVITY). Basically, a `[` or `]` for the range input would mean the bound is included.

From the example in the docs:

```js
const { data, error } = await supabase
  .from('countries')
  .select('name, id, population_range_millions')
  .rangeLt('population_range_millions', '[150, 250]')
```

Brackets `[]` are used. For not including the bounds, parens `()` should be used as per the PostgreSQL docs.

**Comment by kiwicopple** [comment]
Hey @madleo-dk - I'll close this for now, but if steve's solution doesn't work for you feel free to comment and we can re-open
