### ISSUE TITLE
Int8 and Numerical columns returning incorrectly (rounded)

### ISSUE THREAD

**Issue by addisonschultz** [supabase/postgrest-js#273]
# Bug report

## Describe the bug

When using `int8` and `numerical` columns, using the `supabase-js` client will return a rounded (wrong precision) number back. 

I've verified the data is correct both in the Supabase UI (table view), and even returns correctly via the SQL Editor. Additionally, I've verified it's incorrect by making sure the precision of the Numerical unit is set as it should be (also via SQL).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create database with numerical OR int8 column
2. Insert 1+ rows with data - For example: `3458764526536546760`
3. Via JS client, `supabase.from(table_name).select()` the table
4. See that the retrieved value is rounded (in my case with the number above: `3458764526536547000`)
5. Head to SQL editor, and select the same table via SQL (SELECT * from table_name), and verify the data is returned as expected

## Expected behavior

The number should return as expected (not rounded)

## System information

- OS: MacOS
- Browser: Chrome
- Version of supabase-js: `v1.35.3`
- Version of Node.js: `v16.13.0`

**Comment by soedirgo** [comment]
This is because numbers in JS are float64, so if your number is more than `Number.MAX_SAFE_INTEGER === 9007199254740991` it won't be represented correctly.

An alternative is to cast it to `text`: `supabase.from(table_name).select('id, num::text')` and manually convert them to `BigInt`.

I understand the correctness issue can be unacceptable to some - let me know what your thoughts are about this.

**Comment by addisonschultz** [comment]
Thanks for the explanation - This does make sense to me, but was not expected (My JS knowledge doesn't go quite that deep)—Maybe something good for the JS client docs? 

The solution is acceptable, and will work for me—I may also store it in a text type to begin with anyway.

Thanks @steve-chavez @soedirgo, this is now solved for me!
