### ISSUE TITLE
Wrong PostgrestError type

### ISSUE THREAD

**Issue by JulienLecoq** [supabase/postgrest-js#281]
# Bug report

## Describe the bug

The type ``PostgrestError`` from ``node_modules/@supabase/postgrest-js/src/lib/types.ts`` is wrong.
The type has a field ``code: string``.

```ts
export type PostgrestError = {
  message: string
  details: string
  hint: string
  code: string
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to ``node_modules/@supabase/postgrest-js/src/lib/types.ts`` from a supabase client project that has this lib.
3. Scroll down to the type ``PostgrestError``

## Expected behavior

The type should have a field ``code: number`` like the real error result from a select call from the supabase client lib.

```ts
export type PostgrestError = {
  message: string
  details: string
  hint: string
  code: number
}
```

**Comment by steve-chavez** [comment]
Note that code is not always a number, see: https://www.postgresql.org/docs/current/errcodes-appendix.html

There are some codes like `42P01`(undefined table)
