### ISSUE TITLE
API no working reliably (FetchError: Unexpected token < in JSON at position 1) 

### ISSUE THREAD

**Issue by give-my-certificate** [supabase/postgrest-js#282]
# Bug report

## Describe the bug

Calling Supabase API and RPC functions sometimes gives the following error "FetchError: Unexpected token < in JSON at position 1" 

## To Reproduce

No general way to reproduce it as it is an intermittent issue probably related to server performance or how Supabase provisions the Postgres cluster. But chances are that you can query your logs for 500 errors or look into your GA (Google Analytics) and you will find some there.

## Expected behavior

API should work as expected and not only sometimes.

## Screenshots

![image](https://user-images.githubusercontent.com/85610381/168421880-18ef4adf-58a1-4164-925a-6a72c487495f.png)

![image](https://user-images.githubusercontent.com/85610381/168421996-65290996-e2d2-4ed0-9772-56e93e7f2df4.png)

![image](https://user-images.githubusercontent.com/85610381/168422448-7309389c-709d-421c-af49-f413976649b1.png)

## Additional context

Initially, I was getting a "FetchError: Unexpected token < in JSON at position 1" error at the application level so I started looking deeper and find out that Cloudflare is sending and timeout response that can not be decoded as a JSON response and hence the error.

So I look into the logs and found that there are logs with 522 and 524 status codes. I thought that this could be an issue with the server resources and checked for the server loads but that is not the case here as evident by the screenshot attached.

Tried raising the issue with Supabase support and received the most unhelpful response that is possible and they never reply to the follow-up emails.

**Comment by servedbyskull** [comment]
ran into same issue today! :|

**Comment by steve-chavez** [comment]
This one was solved with https://github.com/PostgREST/postgrest/pull/2449/ and released on [v10.1.0](https://github.com/PostgREST/postgrest/releases/tag/v10.1.0). This version(actually v10.1.1)  is already deployed to all supabase projects.

If a timeout happens, nowadays a 504 Gateway timeout status will be reported with the `Timed out acquiring connection from connection pool` error message.

Will close for now. Please reopen if the error persists.
