### ISSUE TITLE
Supabase inner join not working with Typescript.

### ISSUE THREAD

**Issue by roker15** [supabase/postgrest-js#315]
```
const { data, error } = await supabase<Messages>
  .from('messages')
  .select('*, users!inner(*)')
  .eq('users.username', 'Jane')
```
this shows Type error at `users.username`

**Comment by soedirgo** [comment]
Sorry for the late reply. Can you try this with `@supabase/supabase-js@rc`? We'll release this as v2 soon - v1 likely won't be updated from then on.

**Comment by roker15** [comment]
> Sorry for the late reply. Can you try this with `@supabase/supabase-js@rc`? We'll release this as v2 soon - v1 likely won't be updated from then on.

What is rc? When u releasing v2

**Comment by soedirgo** [comment]
It's the release candidate for the new version: https://supabase.com/docs/reference/javascript/next/release-notes

Current plan is to release v2 next week.
