### ISSUE TITLE
Allow overriding default schema in `from` and `rpc`

### ISSUE THREAD

**Issue by osaxma** [supabase/postgrest-js#318]
# Feature request
> _This request was originally filed at https://github.com/supabase-community/supabase-flutter/issues/206_

## Is your feature request related to a problem? Please describe.

Currently it's only possible to use a single schema -- i.e. the one passed to the client upon instantiation.

## Describe the solution you'd like

In some cases, I would like to run a query or invoke an rpc on a different schema than the one given to the client initially such as:

```ts
const client = PostgrestClient('url', {schema: 'public'});

// some where else in the app
const { data, error } = await supabase.from('table_name', 'schema_name' ).select()
// or
const { data, error } = await supabase.rpc('function_name', 'another_schema_name')
```

In both cases, if no schema is given, then the default schema from the client is used. 

## Describe alternatives you've considered

Creating multiple clients (one per schema) seems like the only option but it'd be much easier and cleaner to use the same client.

**Comment by soedirgo** [comment]
Does this look like what you want? https://github.com/supabase/postgrest-js/issues/280

**Comment by osaxma** [comment]
@soedirgo yeah I believe the same with different proposed solution(s) ... I'll close this and follow up there..

Thanks 🙏
