### ISSUE TITLE
rpc: Setting the transaction isolation level

### ISSUE THREAD

**Issue by steve-chavez** [supabase/postgrest-js#320]
Hi, is it possible to set the transaction isolation level instead doing something like this?

```plpgsql
-- this comes with drawbacks, such as not being able to COMMIT or ROLLBACK
create or replace procedure foo_proc()
set default_transaction_isolation = 'serializable'
as $$
begin
    insert into tab1 values (1);
end;
$$ language plpgsql;
```

In my particular case I need to use serializable transactions for a non-trivial use case. Better yet, is there a way to wrap any statements with a classic `BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE; <statements>; COMMIT;` transaction and set the isolation level outside?

_Originally posted by @ricogallo in https://github.com/supabase/supabase/discussions/8798_

---

https://github.com/PostgREST/postgrest/issues/2468

**Comment by ricogallo** [comment]
Maybe we can have an interface similar to what edgedb has done?

```js
const email = "timmy@edgedb.com"

await client.transaction(async tx => {
  await tx.execute(
    `insert User { email := <str>$email }`,
    { email },
  )

  await sendWelcomeEmail(email);

  await tx.execute(
    `insert LoginHistory {
      user := (select User filter .email = <str>$email),
      timestamp := datetime_current()
    }`,
    { email },
  )
})
```

Or maybe a more supabase-y approach might be:
```js
const { data, error } = await supabase
  .begin({ isolation: 'serialize', access: 'read-write'} )
  .from('cities')
  .insert([{ name: 'The Shire', country_id: 554 }])
  .insert([{ name: 'Gondor', country_id: 555 }])
  .savePoint()
  .insert([{ name: 'Mordor', country_id: 556 }])
  .commit();
```

**Comment by steve-chavez** [comment]
Just to point out this is possible on PostgREST v11 https://postgrest.org/en/stable/references/transactions.html#isolation-lvl. 

For this you have to mark the SQL function with `default_transaction_isolation`.

```sql
CREATE OR REPLACE FUNCTION myfunc()
RETURNS text as $$
  SELECT 'hello';
$$
LANGUAGE SQL
SET default_transaction_isolation TO 'serializable';
```

v11 should be deployed soon. Please subscribe [here](https://github.com/supabase/postgres/pull/628) for knowing when it's ready.

**Comment by ricogallo** [comment]
Thanks for your effort!
