### ISSUE TITLE
Bulk Delete

### ISSUE THREAD

**Issue by ThijsDeR** [supabase/postgrest-js#321]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to bulk delete everything in the table, but it needs a where clause that I cannot fill with an empty clause.

## Describe the solution you'd like

A bulkdelete() function or a way to have an empty clause.

## Describe alternatives you've considered

I tried having different matching ids with regex or other things to delete the whole table content

## Additional context

No Context.

**Comment by steve-chavez** [comment]
> I want to bulk delete everything in the table, but it needs a where clause that I cannot fill with an empty clause.

Could you share the error message you get? 

This seems related to https://github.com/eradman/pg-safeupdate, but want to be certain.

**Comment by soedirgo** [comment]
If you're *really* sure about deleting all rows in the table, you can do:
```ts
await supabase
  .from('t')
  .delete()
  .eq('id', 42)
await supabase
  .from('t')
  .delete()
  .neq('id', 42)
```

**Comment by steve-chavez** [comment]
Limiting the amount of deleted rows could also be an option: https://postgrest.org/en/stable/api.html#limited-updates-deletions

Not sure if safeupdate will allow that.

**Comment by soedirgo** [comment]
To delete all rows in one request:
```ts
await supabase
  .from('t')
  .delete()
  .or('id.eq.0,id.neq.0')
```
Adjust according to your column name and type. Basically you just need filters that always evaluates to true.

I'll close this for now, but feel free to reopen if that doesn't work.
