### ISSUE TITLE
Support bulk update with array of partial items

### ISSUE THREAD

**Issue by aiibe** [supabase/postgrest-js#325]
I am able to bulk update items (even without a filter) with an array of partial items.
Works fine but I had to cast my values `.update(values as unknown as Partial<T>)` while they are actually `Partial<T>[]`.
Looking in the source code, it seems like `update` accept only a value at a time.

**Comment by soedirgo** [comment]
Does this work with `@supabase/postgrest-js@rc` or `@supabase/supabase-js@rc`? We'll be releasing these as new versions soon.

**Comment by aiibe** [comment]
@soedirgo Haven't test with `@supabase/postgrest-js@rc`. I used `@supabase/postgrest-js` latest release.

**Comment by soedirgo** [comment]
Actually, rereading this again, does bulk update actually work for you right now? AFAIK this is still a WIP upstream: https://github.com/PostgREST/postgrest/issues/1959

cc @steve-chavez

**Comment by soedirgo** [comment]
Thought we had an issue for this - sorry about that! I'll repurpose this issue to track the bulk update feature.

**Comment by soedirgo** [comment]
Closing in favor of https://github.com/supabase/postgrest-js/issues/174
