### ISSUE TITLE
Group By Method

### ISSUE THREAD

**Issue by jdgamble555** [supabase/postgrest-js#332]
# Feature request

This seems like a basic feature request I thought would already exist, but apparently not.

It would be nice to be able to say:

```sql
SELECT COUNT(*), PLAYER FROM GAMES GROUP BY PLAYER
```

To supabase js:

```typescript
const { data, error } = await supabase
        .from('games')
        .select('count(*), player'),group('player');
```

This would need to work with nested values as well and should be repeatable.

Seems like a decent request.

J

**Comment by soedirgo** [comment]
Hey @jdgamble555! This seems related to https://github.com/supabase/postgrest-js/issues/206, so closing this in favor of that one. It needs an upstream patch outside of the client lib.
