### ISSUE TITLE
Should `update` use Partial<Row>?

### ISSUE THREAD

**Issue by xxRockOnxx** [supabase/postgrest-js#349]
# Bug report

## Describe the bug
Context: https://github.com/supabase/postgrest-js/blob/v1.0.0/src/PostgrestQueryBuilder.ts#L248

When updating, it currently asks for the whole columns.

Looking at the source, there's a `PATCH` request which I assume updates only what's given to it.

I could submit a PR adding `Partial<>` on it if it should be.

## To Reproduce

- generate types
- do an update operation

## Expected behavior

Allow specific column to be updated

## Screenshots

None

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

None

**Comment by soedirgo** [comment]
Do you have a repro case where it's not making columns optional? The typegen should be making `Relation['Update']` columns optional, e.g.:

https://github.com/supabase/postgrest-js/blob/94db7098ef9d75766b8ca84b1e888f34a3eb759d/test/types.ts#L19-L24

**Comment by xxRockOnxx** [comment]
@soedirgo the typegen on my end was wrong. i had to update some columns/properties manually and made a mistake. closing this now.

on a related note, is there a way to have typgen make some columns as `never`? e.g `created_at` or `user_id`
just so we could avoid this kind of rookie mistake due to manual editing.

**Comment by soedirgo** [comment]
The types reflect the database, so if you make the column generated always, it'll be typed as `never`. E.g.:
```plpgsql
create table my_table (created_at timestamptz generated always as (now()) stored);
```
