### ISSUE TITLE
Seems like the types for many to many relationships are not working in v2

### ISSUE THREAD

**Issue by mzalevski** [supabase/postgrest-js#355]
Consider following generated types:
```typescript
export interface Database {
  public: {
    Tables: {
      users_skills: {
        Row: {
          user_id: string;
          skill_id: number;
        };
      };
      users: {
        Row: {
          id: string;
          created_at: string;
          name: string | null;
        };
      };
      skills: {
        Row: {
          id: number;
          created_at: string;
          name: string;
        };
      };
    };
  };
}
```
when I try to `supabase.from("users").select("*,skills(*)")` I get
```typescript
{
    id: string;
    created_at: string;
    name: string | null;
} & {
    skills: unknown;
}
```
I tried some things from the postgrest docs but nothing is working. Am I doing something wrong or is this inference not ready yet?

**Comment by soedirgo** [comment]
Hey there, typings for embedded tables is still a WIP, but we have a [PR](https://github.com/supabase/postgrest-js/pull/345) that allows you to override the return type.

**Comment by mzalevski** [comment]
Thanks @soedirgo. I'll be waiting then :)

**Comment by soedirgo** [comment]
Closing this as we've since added typings for embedded tables
