### ISSUE TITLE
Cannot use filter or modifiers on rpc call

### ISSUE THREAD

**Issue by N00nDay** [supabase/postgrest-js#372]
# Bug report

## Describe the bug

When chaining filters or modifiers to an rpc function as documented [here](https://supabase.com/docs/reference/javascript/rpc#call-a-postgres-function-with-filters) the filter and modifiers are ignored and all records are returned.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table `options` with 50 records [id, value]
2. Create a function `fetch_options` that fetches all records in the `options` table
3. Call the function with `await supabase.rpc('fetch_options').ilike('%' + 'some partial value' + '%').limit(25);`

## Expected behavior

Only records matching the filter and modifier are returned instead of all records.

## System information

- OS: macOS
- Browser: chrome
- Version of supabase-js: 2.1.0
- Version of Node.js: 16.15.0

**Comment by steve-chavez** [comment]
@N00nDay Could you provide a reproducible example? Table with sample data, the function plus a JS snippet would be great.

Note: RPC filters [are tested](https://github.com/supabase/postgrest-js/blob/master/test/filters.ts#L554-L567) to work.

**Comment by N00nDay** [comment]
> @N00nDay Could you provide a reproducible example? Table with sample data, the function plus a JS snippet would be great.
> 
> 
> 
> Note: RPC filters [are tested](https://github.com/supabase/postgrest-js/blob/master/test/filters.ts#L554-L567) to work.

2 things I noticed when looking at the tested rod function 'get_username_and_status':

1. The function is expressly set as immutable. 
2. The table columns being returned matches the table columns being queried. 

Could either of these be the cause? I will work on a reproduction but I am curious if either of those jump out as a possible issue/difference that may be causing this.

**Comment by N00nDay** [comment]
> > Could either of these be the cause?
> > 
> > 1. The function is expressly set as immutable.
> 
> Not really, there tests done at the REST level [here](https://github.com/PostgREST/postgrest/blob/315b01ebf7da143a0756748d33fb37d7a953c8c0/test/spec/Feature/Query/RpcSpec.hs#L209-L217) with a function [that's not immutable](https://github.com/PostgREST/postgrest/blob/315b01ebf7da143a0756748d33fb37d7a953c8c0/test/spec/fixtures/schema.sql#L999-L1003).
> 
> > The table columns being returned matches the table columns being queried.
> 
> That's strange.
> 
> > CREATE OR REPLACE FUNCTION fetch_customers()
> > RETURNS TABLE ( id bigint, value text, subtext text) AS
> > BODY
> > BEGIN
> > RETURN QUERY EXECUTE format(
> > 'SELECT id, full_name, address FROM customers ORDER BY full_name ASC;');
> > END;
> > BODY
> > LANGUAGE plpgsql;
> 
> Why do you need to change the `SELECT` columns inside the function if `supabase-js` can do it? Usually users use dynamic sql for things like GROUP BY which cannot be done directly with `supabase-js`.
> 
> That could be the issue, we could confirm with a reproducible example.

I don't know why I never thought of this and you are completely right which I love because I would prefer to avoid `rpc` as much as possible to keep all my database calls in one place. You sir are a genius.
