### ISSUE TITLE
Mismatch with join subquery between SQL execution and Postgrest results

### ISSUE THREAD

**Issue by Edo-San** [supabase/postgrest-js#384]
# Bug report

Disclaimer: I may be doing something wrong, or I might be missing something, somewhere. In this case, this may be a nice example of a not-that-trivial-yet-not-that-rare use case to include in the docs? :D

## Describe the bug

When calling a SQL function with a join on a subquery, those results are not shown in the Postgrest response, while they are there when the same function is called directly in SQL.

## To Reproduce

Let's start with some context. This is a stripped-down example DB representation.

`languages` table
| id | label   |
|----|---------|
| en | English |
| fr | French |

`cards` table
| id      |
|---------|
| 01DE001 |
| 01DE002 |

`localized_cards` table (PK is made of `card_id` and `language_id` and they are both FKs)
| card_id | language_id | name        | description        |
|---------|-------------|-------------|--------------------|
| 01DE001 | en          | Test name 1 | Test description 1 |
| 01DE002 | en          | Test name 2 | Test description 2 |

`regions` table
| id | code        |
|----|-------------|
| 1  | region1code |
| 2  | region2code |

`localized_regions` table (PK is made of `region_id` and `language_id` and they are both FKs)
| region_id | language_id | name     |
|-----------|-------------|----------|
| 1         | en          | Region 1 name |
| 2         | en          | Region 2 name |

`pivot_cards_regions` table, which keeps track of the many-to-many relationship between `cards` and `regions` (PK is made of `card_id` and `region_id` and they are both FKs)
| card_id | region_id |
|---------|-----------|
| 01DE001 | 1         |
| 01DE001 | 2         |

I created a SQL function that, given a `card_id` and a `language_id` is able to return a row that contains the card id, the localized name and description for the card with the provided card id, and the language with the provided language id, and the list of regions related to that card, formatted as an array of region names translated in the provided language.
Below is the function implementation and a test result when run through SQL directly.
```
create or replace function get_localized_card(_card_id text, _language_id text)
  returns table(
    id text,
    name text,
    description text,
    regions text[]
  )
as $$
select
  cards.id,
  localized_cards.name,
  localized_cards.description,
  rg.regions
from cards
join localized_cards on localized_cards.card_id = cards.id
-- join regions
left join (
  select pivot_cards_regions.card_id, array_agg(localized_regions.name) as regions
  from pivot_cards_regions
  join regions on regions.id = pivot_cards_regions.region_id
  join localized_regions on localized_regions.region_id = regions.id and localized_regions.language_id = _language_id
  group by pivot_cards_regions.card_id
) rg on cards.id = rg.card_id
localized_card_subtypes.language_id = _language_id
where cards.id = _card_id
and localized_cards.language_id = _language_id;
$$ language sql stable;
```

Example of query run
`select get_localized_card('01DE001', 'en')`
Query result, as seen in Supabase SQL editor
`(01DE001,"Test name 1","Test description 1",{"Region 1 name", "Region 2 name"})`

If I run the same function via Supabase JS client or via a direct request to the Supabase Postgrest endpoint, I get this result:
`[
	{
		"id": "01DE001",
		"name": "Test name 1",
		"description": "Test description 1",
		"regions": null
	}
]`

It looks like the query is right on itself, but the result is not correctly exposed through Postgrest.
Here is an example of the GET request made directly via Supabase Postgrest endpoint:
`https://xxx.supabase.co/rest/v1/rpc/get_localized_card?_card_id=01DE001&_language_id=en`

## Expected behavior

I'd expect to have an array of `regions` instead of a `null` value.

**Comment by steve-chavez** [comment]
Do you have RLS policies on the `regions` table?

Try doing this to reproduce on plain SQL:

```sql
begin;
set local role authenticated;
select get_localized_card('01DE001', 'en');
end;
```

**Comment by Edo-San** [comment]
Hey, @steve-chavez thanks for the answer! :D
I knew I was overlooking something.. you are indeed right, I still had to set up RLS policies on the newly joined tables.

Everything is working as expected, now.
Will close this, TYVM!

**Comment by TylerAHolden** [comment]
Just wasted an embarrassing amount of time from this. I wish the "no active RLS" message on the top right was like super obvious and red or something. blinking would be even better.

**Comment by steve-chavez** [comment]
@TylerAHolden Good suggestion. Perhaps showing the role on the SQL editor with a "RLS not applied" notice. Will pass this feedback to the frontend team.
