### ISSUE TITLE
Unsupported Media Type on .explain query

### ISSUE THREAD

**Issue by jsbrain** [supabase/postgrest-js#392]
# Bug report

## Describe the bug

`.explain` results in media error.

## To Reproduce

```ts
const query = await supabase.from('test').select('*').explain();
```

results in 

```ts
{
  error: {
    code: 'PGRST107',
    details: null,
    hint: null,
    message: 'None of these media types are available: application/vnd.pgrst.plan+text'
  },
  data: null,
  count: null,
  status: 415,
  statusText: 'Unsupported Media Type'
}
```

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: 2.4.1
- Version of Node.js: 16

**Comment by steve-chavez** [comment]
Hello, to use explain first you need to enable server side with:

```sql
alter role authenticator set pgrst.db_plan_enabled to true;
notify pgrst, 'reload config';
```

Let me know if that works.

**Comment by jsbrain** [comment]
Thanks @steve-chavez  for the clarification.

Probably worth adding this to [the docs](https://supabase.com/docs/reference/javascript/introduction).

Looks like so far `.explain` isn't documented at all!?

**Comment by jsbrain** [comment]
And unfortunately no, it did not work ... also restarted the deployment after I ran the commands but no change.

I'm on self-hosted btw. with [this config](https://github.com/supabase/supabase/blob/f3031fa24fd4a65e7d48f079db45a0cd3ee0311c/docker/docker-compose.yml).

**Comment by steve-chavez** [comment]
If you're on self-hosted, you can add `PGRST_DB_PLAN_ENABLED: true` [here](https://github.com/supabase/supabase/blob/f3031fa24fd4a65e7d48f079db45a0cd3ee0311c/docker/docker-compose.yml#L110-L114).

**Comment by jsbrain** [comment]
Still the same error ...

I tried to send a request directly to postgrest via Postman, setting the accept error as: [shown here](https://postgrest.org/en/stable/configuration.html?highlight=PGRST_DB_PLAN_ENABLED#db-plan-enabled:~:text=Accept%3A%20application/vnd.pgrst.plan).

Output:

```
{
    "code": "PGRST107",
    "details": null,
    "hint": null,
    "message": "None of these media types are available: application/vnd.pgrst.plan+json"
}
``

Something is odd ... 🤔

**Comment by steve-chavez** [comment]
You're using an old version https://github.com/supabase/supabase/blob/f3031fa24fd4a65e7d48f079db45a0cd3ee0311c/docker/docker-compose.yml#L104

Change it to v10.1.1

**Comment by jsbrain** [comment]
Well, that solves the mystery. I was somehow under the impression that the docker-compose is up to date with the js clients.

Thanks so much for your help!
