### ISSUE TITLE
Insert & Update should return the ID of the new elements

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgrest-js#4]
Possible implementation:

- Return an object with ID if there is only a single element inserted/updated
- Return and array of objects with IDs if there is bulk insert/update
- Allow the user to pass some options to return the whole record that was created

**Comment by Laplo** [comment]
When doing an insert, id of the inserted object is located on the Location header but agree for others :)

**Comment by kiwicopple** [comment]
See: postgrest.org/en/v6.0/api.html?highlight=inserts#insertions-updates

add header: 

```
Prefer: return=representation
```

**Comment by awalias** [comment]
fixed in 0.5.0

**Comment by awalias** [comment]
note: the change I made adds the representation header to every insert and update, we may want to add the ability to remove or even add `Prefer: return=minimal` instead in a future release
