### ISSUE TITLE
Typing ParserError when selecting JSONB field with double quotes

### ISSUE THREAD

**Issue by kevcodez** [supabase/postgrest-js#413]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When selecting a JSONB field using `jsonb_column->"field_name"`, the type cannot be determined. Whereas using `jsonb_column->field_name` works.

## To Reproduce

```
authReadOnly
        .from('projects')
        .select(
          `
          id,
          infrastructure_config->"region"
        `
        )
```

>  Property 'region' does not exist on type 'ParserError<"Unexpected input: ->\"region\"">'.

## Expected behavior

The type should be parsed correctly, even when using double quotes.

**Comment by steve-chavez** [comment]
This should be purely a `postgrest-js` issue.  postgREST does allow quoting when using the arrow operators:

```bash
curl 'localhost:3000/complex_items?select=settings->foo->"bar"'

[{"bar":"baz"},
 {"bar":"baz"},
 {"bar":"baz"}]
```

**Comment by kevcodez** [comment]
@steve-chavez +1 - the code executes just fine, it's only the types that are off 👌

**Comment by tvogel** [comment]
I think, this also got fixed by https://github.com/supabase/postgrest-js/commit/c69ef50e633e5bf96da8856d769b9f9a11b0e34d .

**Comment by kevcodez** [comment]
Yup, looking good @tvogel 🥳
