### ISSUE TITLE
Javascript RPC Typescript error: Argument of type 'string' is not assignable to parameter of type...

### ISSUE THREAD

**Issue by hichana** [supabase/postgrest-js#420]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In the Javascript documentation an example is given for using rpc to call custom functions:
https://supabase.com/docs/reference/javascript/using-filters
`const { data, error } = await supabase.rpc('hello_world')`

In typescript, the following error is thrown: 
`Argument of type 'string' is not assignable to parameter of type 'never'.ts(2345)`

To mitigate the error I had to add a custom typescript definition for the supabase client:

```
// supabaseCustom.d.ts

import { PostgrestBuilder } from '@supabase/postgrest-js';
import { SupabaseClient } from '@supabase/supabase-js';

declare module '@supabase/supabase-js' {
  interface SupabaseClient {
    rpc<ResponseType, ParamsType>(
      fn: string,
      params?: ParamsType
    ): PostgrestBuilder<ResponseType>;
  }
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. attempt to use this code `const { data, error } = await supabase.rpc('hello_world')`
2. 
## Expected behavior

There should be no ts error

**Comment by soedirgo** [comment]
Hi, can you put up a repo so I can reproduce the issue? We have a test [here](https://github.com/supabase/postgrest-js/blob/ad746086ceb7a56c126e547f1aec9c01e0b54286/test/index.test-d.ts#L60) which doesn't have the issue above, so not sure how that happens.

**Comment by abeisleem** [comment]
Experiencing the same issue using: 
    "@supabase/auth-helpers-nextjs": "^0.7.4",
    "@supabase/auth-ui-shared": "^0.1.7",
    "@supabase/supabase-js": "^2.33.2",
    
 Specifically, I'm using the createClientComponentClient from "@supabase/auth-helpers-nextjs"

**Comment by abeisleem** [comment]
@hichana ... I am no longer facing this issue. Make sure your generated types are up-to-date with the database. Generate with `supabase gen types typescript --project-id abcdefghijklmnopqrst > database.types.ts`. This will create a `hello_world` db Function for you database.types.ts. I'm assuming you're initializing your supabase client with the Database type (ex. `createClient<Database>(...)`.  This is what's causing that error since your database.types.ts is not up-to-date with the db.

**Comment by ajesuscode** [comment]
I can confirm  @abeisleem you provided correct solution, thank you!

**Comment by zillBoy** [comment]
Hi, I believe this issue can be closed.
The solution provided by @abeisleem is working fine, thanks for confirming the fix @ajesuscode. 

For me, I used the supabase website to generate the types
Link: https://supabase.com/docs/guides/api/rest/generating-types

![Screenshot_3300](https://github.com/supabase/postgrest-js/assets/41048737/72fb7fcf-66b6-4a1a-8d87-4b6231c27290)
