### ISSUE TITLE
`rpc` not automatically typing response

### ISSUE THREAD

**Issue by bombillazo** [supabase/postgrest-js#430]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The supabase client is not automatically typing RPC functions all responses based on the generated Database type.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a DB function in your database
2. Generate DB types with CLI
3. Create a supabase client, type with generated Database type.
```ts
export const supabase = createClient<Database>(
  env.SUPABASE_URL,
  env.SUPABASE_ANON_KEY,
);
```
4. Use the RPC function with the client.
```tsx
const response = await supabase.rpc('my_function', data);
```
6. Response is untyped

## Expected behavior

The supabase client automatically types the RPC response based on the Database schema types

## Screenshots

![image](https://github.com/supabase/supabase-js/assets/44002321/b23d5c15-1722-4a13-add0-ad273766c38f)

Working if the types are explicitly passed:

![image](https://github.com/supabase/supabase-js/assets/44002321/cdf8cb15-477c-4706-8b09-2e281c62d169)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by soedirgo** [comment]
Can you provide your CLI version & supabase-js/postgrest-js versions? We have a test for RPC return types so not sure how this happened.

**Comment by bombillazo** [comment]
i think this is solved, probably an intermediary cli version was fixed and now works. closing :)
