### ISSUE TITLE
How to set RPC to send by GET with query params

### ISSUE THREAD

**Issue by digoburigo** [supabase/postgrest-js#438]
# Improve documentation

## Link 
https://supabase.github.io/postgrest-js/v2/classes/PostgrestClient.html#rpc

How to make a RPC call with GET and query params

## Describe the problem

Don't have an example or how to do it

Example:
`GET https://postgrest-url.domain/rpc/{function}?{param}={value}...`

**Comment by digoburigo** [comment]
My use case is a postgrest connected to a replica database for read only, so POST requests don't work.
Error that occurs is referenced in this [StackOverflow issue](https://stackoverflow.com/questions/24384407/cannot-set-transaction-read-write-mode-during-recovery-error), for example

**Comment by steve-chavez** [comment]
@digoburigo If you mark your functions with `STABLE` or `IMMUTABLE`:

```sql
CREATE FUNCTION --.. 
$$;
LANGUAGE SQL STABLE;
```

Then PostgREST will run it under a `READ ONLY` access mode. That should avoid that error.

For more details, see https://postgrest.org/en/stable/references/transactions.html#access-mode.

---

That being said I think we could add a parameter to `rpc` for using a GET. Maybe on `options` (`{options: { get: true} }`.

**Comment by digoburigo** [comment]
@steve-chavez oh nice, thanks for the info. Must have looked better in postgrest docs.
For the options in the `postgrest-js` would be nice to have.
Feel free to close this issue then!
