### ISSUE TITLE
Type error: referencing missing column `count`

### ISSUE THREAD

**Issue by davidchalifoux** [supabase/postgrest-js#447]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After upgrading `@supabase/supabase-js` to `2.26.0`, I'm now getting a type error when querying `count` for a nested relationship. The API is returning the count exactly as before, so it's only a type issue.

## To Reproduce

- Query the `count` of a nested relationship.
- Try to reference said value

Example query:
```js
const response = await supabase
    .from("brands")
    .select(
      "*, brand_categories!brands_category_id_fkey(*), brand_subcategories(*, brand_categories(*)), brand_statuses(*), brand_locations(count)",
      { count: "estimated", head: false }
    );
```
In this example, `brand_locations(count)` is what's causing the error.
The returned type for that field is `SelectQueryError` even though no error is thrown from the API.

## Expected behavior

The returned type of a `count` should not be `SelectQueryError`.

## Screenshots

![Screenshot 2023-07-20 at 10 23 40 AM](https://github.com/supabase/supabase-js/assets/3289533/c7a6bb45-5217-4388-bc40-c52affd38e34)

## System information

- OS: macOS 13.5
- Version of supabase-js: `v2.26.0`
- Version of Node.js: `v18.17.0`

**Comment by soedirgo** [comment]
Thanks David, I'll try to reproduce this. Is `count` a normal column of `brand_locations`? Or a computed column etc.?

**Comment by davidchalifoux** [comment]
@soedirgo Thank you!
No, it is not a normal or computed column.

**Comment by davidchalifoux** [comment]
It's actually happening to me with a much simpler query:
```ts
const res = await supabase
      .from("brand_locations")
      .select("count", { count: "estimated", head: true })
      .eq("brand_id", brandId);
```

Again, it's returning `SelectQueryError<"Referencing missing column `count`">`.
I also tested it on other tables in my database, and it's happening with every one of them.
Could it be an issue with `supabase gen types`?

**Comment by jasonpanosso** [comment]
This is happening to me with this query:
```typescript
  const someQuery = await supabase
    .from('someTable')
    .select(
      `id,
       fk:foreign_key_id(id, name)
      `
    )
```

I believe it has to do with [this pr](https://github.com/supabase/postgrest-js/pull/436)

I've verified that my types file is correct, the column `foreign_key_id` exists on `someTable`, and is configured as foreign key to the table I expect it to be referencing(confirmed in types file), and the column `name` exists on aforementioned table.

**Comment by jasonpanosso** [comment]
@soedirgo did you ever get a chance to test? Curious if this is intended behavior, or a bug

**Comment by viniciusdel** [comment]
I am having the same issue. It generates the proper types but the "count" is not marked in typescript so it's screaming.

![image](https://github.com/user-attachments/assets/fc4ec299-39cf-4e31-a548-90c242faa2f2)
![image](https://github.com/user-attachments/assets/0d848e2f-8a5b-4cc4-bbd7-99e43d137e42)
