### ISSUE TITLE
Spread operator causes Typescript ParserError

### ISSUE THREAD

**Issue by KrisBraun** [supabase/postgrest-js#459]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Using the new PostgREST spread operator works, but leads to a Typescript error:

`error TS2339: Property 'invitees' does not exist on type 'ParserError<"Expected identifier at `...contact(id,name,email,contact_user_id))`">`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add spread (`...`) to a `select()`.
2. Compile with `tsc`

## Expected behavior

Types should successfully be generated when queries include the spread operator.

## System information

- Version of supabase-js: 2.32.0
- Version of Node.js: Cloudflare Workers

**Comment by nathantew14** [comment]
I am facing the same issue. Although it works, the typescript is all fked up. Is there any workaround besides forcing the type?

**Comment by destinio** [comment]
Getting the same 
```
Property 'number' does not exist on type 'ParserError<"Expected identifier at `...chapters(title, number) \n  `">'.ts(2339)
```

## Version
```
    "@supabase/auth-helpers-nextjs": "^0.8.7",
    "@supabase/supabase-js": "^2.38.4",
```

```
import { Database } from '@/supabase'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import Link from 'next/link'

export default async function UserPage() {
  const supabase = createServerComponentClient<Database>({ cookies })

  const { data, error } = await supabase.from('favorites').select(`
    id, ...chapters(title, number) 
  `)

  if (!data) {
    return <h2>No chapters</h2>
  }

  return (
    <>
      <div className='m-auto max-w-4xl'>
        <h3>favorites</h3>
        <div className='flex flex-col'>
          {data.map(f => {
            return (
              <Link href={`/chapters/${String(f.number)}`} key={f.id}>
                {f.title}
              </Link>
            )
          })}
        </div>
      </div>
    </>
  )
}
```

**Comment by arepp23** [comment]
Same issue here. Any way to force the type?

**Comment by Aero56** [comment]
> Same issue here. Any way to force the type?

@arepp23 You can do `.single<Type>();` or `.returns<Type>();`
