### ISSUE TITLE
Implement Support for Embedded Tables

### ISSUE THREAD

**Issue by dragarcia** [supabase/postgrest-js#46]
[Reference](http://postgrest.org/en/v7.0.0/api.html#embedding-through-join-tables).

**Comment by kiwicopple** [comment]
wow. that's awesome

**Comment by dragarcia** [comment]
Main use cases for Embedded Tables
- [x] Using columns from the foreign tables as filters. Already supported 
- [ ] Ordering of query based on foreign table columns. Will be implemented through `.order()`
- [ ] Limiting and using offset for data coming from foreign tables. The functionality of `.range()` is unable to cover this. `.limit()` and `.offset()` will be introduced as alternatives to `.range()` that can cover this use case at the same time.
