### ISSUE TITLE
1.8.1 @supabase/node-fetch dependencies breaks browser builds

### ISSUE THREAD

**Issue by NiklasPor** [supabase/postgrest-js#465]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After installing the latest dependencies (upgrading to version `1.8.1` of this package), browser builds (plain react app), start breaking because global is undefined. This is a classic error when node modules, in this case `@supabase/node-fetch`, are imported in a browser context.

The errors are thrown from this file: ../node_modules/.pnpm/@supabase+node-fetch@2.6.13/node_modules/@supabase/node-fetch/lib/index.mjs

## Expected behavior

Not breaking

## Workaround

Pin your `@supabase/postgrest-js` version to `1.8.0`.

E.g. with pnpm:
```json
// package.json
  "resolutions": {
    "@supabase/postgrest-js": "1.8.0"
  }
```

## Screenshots

![image](https://github.com/supabase/postgrest-js/assets/13211347/e22b7158-02a0-411d-a57f-d896915c71ec)
![image](https://github.com/supabase/postgrest-js/assets/13211347/b38c0106-f619-4855-9302-7cf3c6d4a2ba)

## System information

- OS: Intel macOS Ventura
- Browser: chrome
- Version of supabase-js: `2.33.1`
- Version of Node.js: `18.16.0`

## Additional context

- App is beeing built with Vite in my case
- Related discord issue (I'm not the only one experiencing this): https://discord.com/channels/839993398554656828/1143822827561173092

**Comment by arxpoetica** [comment]
This seems to be broken again with the latest release.

**Comment by silentworks** [comment]
@arxpoetica can you provide some steps to reproduce this please? or provide a minimal reproducible example repo.

**Comment by mkilpatrick** [comment]
https://publint.dev/@supabase/postgrest-js@1.9.0

**Comment by jacob-8** [comment]
Circling back, just wanted to update that there is no bug when using Vite 5 with SvelteKit 2 which also uses @sveltejs/vite-plugin-svelte v3 - https://stackblitz.com/edit/sveltejs-kit-template-default-x9ybq2?file=package.json

**Comment by JTCorrin** [comment]
I've got this issue with sveltekit 2 and vite 5

**Comment by nanaian** [comment]
I ran into this bug following [Creating a Supabase client for SSR | Supabase Docs](https://supabase.com/docs/guides/auth/server-side/creating-a-client?framework=sveltekit&environment=layout).

@supabase/ssr 0.0.10
@supabase/supabase-js 2.32.0
@supabase/node-fetch 2.6.15

**Comment by gpaiva985** [comment]
I've got this issue with supabase using sveltekit 2 and vite 5. 
In my case, it was possible to fix it by updating PNPM to the latest version (v8.15.3).
I deleted the `pnpm-lock.yaml` file, the `.svelte-kit` and `node_modules` folders and ran `pnpm install`.

**Comment by matrixOperator** [comment]
> I've got this issue with supabase using sveltekit 2 and vite 5. In my case, it was possible to fix it by updating PNPM to the latest version (v8.15.3). After that, I deleted the `pnpm-lock.yaml` file, the `.svelte-kit` and `node_modules` folders and ran `pnpm install` and everything worked.

Had exactly the same condition as you, and this solution worked.
Thank you so much!!!

**Comment by weicheng95** [comment]
> I've got this issue with supabase using sveltekit 2 and vite 5. In my case, it was possible to fix it by updating PNPM to the latest version (v8.15.3). After that, I deleted the `pnpm-lock.yaml` file, the `.svelte-kit` and `node_modules` folders and ran `pnpm install` and everything worked.

I tried the solution mentioned above, but unfortunately, I'm still unable to resolve the issue. Do you guys have any other suggestions?

**Comment by RyannGalea** [comment]
> I ran into this bug following [Creating a Supabase client for SSR | Supabase Docs](https://supabase.com/docs/guides/auth/server-side/creating-a-client?framework=sveltekit&environment=layout).
> 
> @supabase/ssr 0.0.10 @supabase/supabase-js 2.32.0 @supabase/node-fetch 2.6.15

Were you able to resolve it?
