### ISSUE TITLE
Error in crossfetch package

### ISSUE THREAD

**Issue by kokecar11** [supabase/postgrest-js#468]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I just upgraded to the latest Supabase-js package **2.33.1** when I try to use the api, 

Uncaught (in promise) SyntaxError: The requested module '/node_modules/.pnpm/cross-fetch@3.1.8/node_modules/cross-fetch/dist/browser-ponyfill.js?v=bd2992b8' does not provide an export named 'default' (at PostgrestBuilder.ts:1:8)

I uninstalled node_modules and tried to reinstall them and I still get the error, all when running supabase-js

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Screenshots
<img width="448" alt="Captura de pantalla 2023-08-24 a la(s) 7 27 11 p m" src="https://github.com/supabase/postgrest-js/assets/42183700/b58b5eb7-4c83-4a86-9947-a0ba674db40d">

## System information

  System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 185.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Brave Browser: 116.1.57.47
    Chrome: 116.0.5845.110
    Safari: 16.6
  npmPackages:
    @builder.io/qwik: ^1.2.8 => 1.2.8
    @builder.io/qwik-city: ^1.2.8 => 1.2.8
    @supabase/supabase-js: ^2.33.1 => 2.33.1
    undici: 5.22.1 => 5.22.1
    vite: 4.3.5 => 4.3.5

**Comment by soedirgo** [comment]
Closing in favor of https://github.com/supabase/supabase-js/issues/845
