### ISSUE TITLE
Wrong type for joins with one-to-one relationships

### ISSUE THREAD

**Issue by probablykasper** [supabase/postgrest-js#471]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have a `profiles` and a `customers` table, with a one-to-one relationship:
```yml
profiles: {
  id: text, primary key
  ...
}
customers: {
  id: references profiles.id, primary key
  stripe_customer_id: text, unique
  ...
}
```

When doing a join between these, TypeScript thinks the type of `customers` is this:
```ts
{
    stripe_customer_id: string;
}[]
```

But when I run the code, this is the actual type I get:
```ts
{
    stripe_customer_id: string;
}
```

So when accessing the `stripe_customer_id` property, I get this type error:
> Property 'stripe_customer_id' does not exist on type '{ stripe_customer_id: string; }[]'.

## To Reproduce

```js
const profile_result = await supabase
	.from('profiles')
	.select('id, customers ( stripe_customer_id )')
	.eq('id', params.id)
	.single()
if (profile_result.data) {
	console.log(profile_result.data.customers.stripe_customer_id)
    //                                        ^
    // Property 'stripe_customer_id' does not exist on
    // type '{ stripe_customer_id: string; }[]'.ts(2339)
}
```

## Expected behavior

The TypeScript type should not be an array for one-to-one relationships. It should match the actual type

## System information

- OS: macOS
- Version of supabase-js: 2.31.0
- Version of Node.js: 18.14.2

## Additional context

Related:
- https://github.com/supabase/supabase-js/issues/723

**Comment by FocusCookie** [comment]
I encountered the same issue today and I found another workaround.

```
const profile_result = await supabase
	.from('profiles')
	.select('id, customers ( stripe_customer_id )')
	.eq('id', params.id)
	.single()
        .returns<YourType[]>();

# type definition
type YourType {
    the type that you expect without the array
}
```

**Comment by timlgl** [comment]
I am experiencing the exact same issue. As my query is rather nested, workarounds are very inconvenient...

Does anyone know, whether an older version does not have this bug included?

**Comment by orels1** [comment]
Seems to still be an issue

**Comment by albertonii** [comment]
Same problem over here, is there a fix for this issue??

**Comment by DhenPadilla** [comment]
Yep, same here! Please fix when possible

**Comment by chrissy0** [comment]
Still a problem, please fix!

**Comment by fvermaut** [comment]
same problem for me

**Comment by sanagurcia** [comment]
Please fix!

**Comment by avallete** [comment]
Hi there,

I believe this bug might have been fixed. I tried to reproduce the issue with the following setup:

### SQL Setup:

```sql
-- Create profiles table
CREATE TABLE profiles (
  id TEXT PRIMARY KEY
);

-- Create customers table with a foreign key to profiles
CREATE TABLE customers (
  id TEXT PRIMARY KEY REFERENCES profiles(id),
  stripe_customer_id TEXT UNIQUE
);

INSERT INTO profiles (id) VALUES ('1');
INSERT INTO customers (id, stripe_customer_id) VALUES ('1', '1');
```

### TypeScript Test:

```ts
const profile_result = await supabase
  .from('profiles')
  .select('id, customers (stripe_customer_id)')
  .single();

console.log(profile_result.data);
```

With this setup, I got the expected results both from a types and runtime perspective:

### TypeScript Types:

```ts
const profile_result: PostgrestSingleResponse<{
  id: string;
  customers: {
    stripe_customer_id: string | null;
  } | null;
}>
```

### Runtime Output:

```json
{
  "id": "1",
  "customers": {
    "stripe_customer_id": "1"
  }
}
```

Could you please check on your end if it's fixed for you as well?

**Comment by probablykasper** [comment]
Looks like it's fixed yeah

**Comment by lorraineS** [comment]
Absolutely not fixed.
![Capture d’écran 2024-09-29 à 09 57 31](https://github.com/user-attachments/assets/96fe4ea9-6746-451a-b440-f2690a649627)

Last version used (2.45.4)

**Comment by hawkcookie** [comment]
I think it will be difficult to investigate without also giving the related SQL schema.



> Absolutely not fixed.
> A one-to-one relationship should not expect an array in this case.
>

**Comment by lorraineS** [comment]
> ```sql
> scraped_site_id
> ```

You are right, I updated my previous message to include thetables to reproduce the issue.

**Comment by lorraineS** [comment]
> I think it will be difficult to investigate without also giving the related SQL schema.
> 
> > Absolutely not fixed.
> > A one-to-one relationship should not expect an array in this case.

You are right, I updated my previous message to include thetables to reproduce the issue.

**Comment by hawkcookie** [comment]
I checked the schema in my environment, and the type relationships generated by Supabase with the same schema you provided were correctly inferred.

<img width="690" alt="スクリーンショット 2024-09-29 19 46 12" src="https://github.com/user-attachments/assets/eff6f7c1-1f49-419b-b880-4422726c327d">

Based on your screenshot, I noticed that not only the one-to-one relationships, but also the text type columns are inferred as any type, which is concerning. Are the types being generated correctly by the Supabase CLI, and is the output file properly generated?


Here’s what I did

- `npx create-next-app -e with-supabase`
- add .env.local to supabase envrioment variables.
- execute your schema sql.
- npx supabase gen types --lang=typescript --project-id XXXXXX --schema public > database.types.ts
- add createServerClient to Database type generated by supabase cli.

``diff
 export const createClient = () => {
-  const cookieStore = cookies();
+       const cookieStore = cookies();

-  return createServerClient(
-    process.env.NEXT_PUBLIC_SUPABASE_URL!,
-    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
-    {
-      cookies: {
-        getAll() {
-          return cookieStore.getAll();
-        },
-        setAll(cookiesToSet) {
-          try {
-            cookiesToSet.forEach(({ name, value, options }) => {
-              cookieStore.set(name, value, options);
-            });
-          } catch (error) {
-            // The `set` method was called from a Server Component.
-            // This can be ignored if you have middleware refreshing
-            // user sessions.
-          }
-        },
-      },
-    },
-  );
+       return createServerClient<Database>(
+               process.env.NEXT_PUBLIC_SUPABASE_URL!,
+               process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
+               {
+                       cookies: {
+                               getAll() {
+                                       return cookieStore.getAll();
+                               },
+                               setAll(cookiesToSet) {
+                                       try {
+                                               cookiesToSet.forEach(({ name, value, options }) => {
+                                                       cookieStore.set(name, value, options);
+                                               });
+                                       } catch (error) {
+                                               // The `set` method was called from a Server Component.
+                                               // This can be ignored if you have middleware refreshing
+                                               // user sessions.
+                                       }
+                               },
+                       },
+               },
+       );
 };
```

> > I think it will be difficult to investigate without also giving the related SQL schema.
> > > Absolutely not fixed.
> > > A one-to-one relationship should not expect an array in this case.
> 
> You are right, I updated my previous message to include the tables to reproduce the issue.

**Comment by lorraineS** [comment]
> J'ai vérifié le schéma dans mon environnement et les relations de type générées par Supabase avec le même schéma que vous avez fourni ont été correctement déduites.
> 
> <img alt="2024-09-29 19 46 12" width="690" src="https://private-user-images.githubusercontent.com/29660904/371847229-eff6f7c1-1f49-419b-b880-4422726c327d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMzEyNjMsIm5iZiI6MTcyODEzMDk2MywicGF0aCI6Ii8yOTY2MDkwNC8zNzE4NDcyMjktZWZmNmY3YzEtMWY0OS00MTliLWI4ODAtNDQyMjcyNmMzMjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDEyMjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NDM4ZThjMDA4YzEwMjBiMzUwMTkzZmEzODM2NDY2YzNjOTRiY2U5Nzk3MDJmYWQwZmNlMTQ3YzAyMWQ1NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oVD6DFiX3KqOIHKkGzy5rjHgg1VSgWSDsJSQLSYKCuk">
> D'après votre capture d'écran, j'ai remarqué que non seulement les relations un à un, mais aussi les colonnes de type texte sont déduites de n'importe quel type, ce qui est inquiétant. Les types sont-ils générés correctement par la CLI Supabase et le fichier de sortie est-il correctement généré ?
> 
> Voilà ce que j'ai fait
> 
> * `npx create-next-app -e with-supabase`
> * ajoutez .env.local aux variables d'environnement supabase.
> * exécutez votre schéma SQL dans le tableau de bord.
> * npx supabase gen types --lang=typescript --project-id XXXXXX --schema public > database.types.ts
> * ajoutez createServerClient au type de base de données généré par supabase cli.
> 
> ```diff
>  export const createClient = () => {
> -  const cookieStore = cookies();
> +       const cookieStore = cookies();
> 
> -  return createServerClient(
> -    process.env.NEXT_PUBLIC_SUPABASE_URL!,
> -    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
> -    {
> -      cookies: {
> -        getAll() {
> -          return cookieStore.getAll();
> -        },
> -        setAll(cookiesToSet) {
> -          try {
> -            cookiesToSet.forEach(({ name, value, options }) => {
> -              cookieStore.set(name, value, options);
> -            });
> -          } catch (error) {
> -            // The `set` method was called from a Server Component.
> -            // This can be ignored if you have middleware refreshing
> -            // user sessions.
> -          }
> -        },
> -      },
> -    },
> -  );
> +       return createServerClient<Database>(
> +               process.env.NEXT_PUBLIC_SUPABASE_URL!,
> +               process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
> +               {
> +                       cookies: {
> +                               getAll() {
> +                                       return cookieStore.getAll();
> +                               },
> +                               setAll(cookiesToSet) {
> +                                       try {
> +                                               cookiesToSet.forEach(({ name, value, options }) => {
> +                                                       cookieStore.set(name, value, options);
> +                                               });
> +                                       } catch (error) {
> +                                               // The `set` method was called from a Server Component.
> +                                               // This can be ignored if you have middleware refreshing
> +                                               // user sessions.
> +                                       }
> +                               },
> +                       },
> +               },
> +       );
>  };
> ```
> 
> > > Je pense qu'il sera difficile d'enquêter sans donner également le schéma SQL associé.
> > > > Absolument pas fixe. 
> > > > Une relation un à un ne devrait pas s'attendre à un tableau dans ce cas.
> > 
> > 
> > Vous avez raison, j'ai mis à jour mon message précédent pour inclure les tableaux pour reproduire le problème.

Thank you, that fixed the problem.

**Comment by elyobo** [comment]
Seems fixed with `.single()` but not without it - the relationship is the same whether `.single()` or not though, it's surprising that you'd get an object with `.single()` and an array normally. Using a foreign key to a primary key on another table is very common and it's very weird that you end up getting an array of results for that.

**Comment by avallete** [comment]
> Seems fixed with `.single()` but not without it - the relationship is the same whether `.single()` or not though, it's surprising that you'd get an object with `.single()` and an array normally. Using a foreign key to a primary key on another table is very common and it's very weird that you end up getting an array of results for that.
> 
> Using `!inner` also resolves it, which is also weird, because the inner join doesn't change the cardinality.

Hi there, would you mind providing a minimal reproduction example of your case with both the SQL to generate the relation and the select query you're running ?

`.single` should only affect the "root result" not the underlying relationship type. If I can reproduce I could investigate into this, please feel free to open a new issue and ping me on it.

**Comment by elyobo** [comment]
For the `.signle()` vs non-single behaviour, I confirmed with the example SQL (after removing some trailing commas!) above to ensure that it wasn't anything of mine.

I'll check now to see whether `!inner` also resolves it.
