### ISSUE TITLE
Postgrest composite type casting error

### ISSUE THREAD

**Issue by Torres1080** [supabase/postgrest-js#475]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After creating a **clone** of my own project I found a problem after executing some functions which relies on a postgrest rpc call. The function itself returns a composite type with the following parameters

```sql
create type tp_minified_application as (
  id bigint,
  assembler tp_company
);
```

where tp_company has the following implementation

```sql
create type tp_company as (
  id text,
  owner text
);
```

The function barely makes a simple select * from a table application and returns a set of tp_minified_application.I've tested it and it works fine. 

```sql
create or replace function browse_minified_applications()
returns setof tp_minified_application as
$browse_minified_applications$
  select A.id, C assembler
  from application A
  join company C on C.id = A.assembler
$browse_minified_applications$ language sql;
```

The problem I'm facing is that when I make the call within my code

```js
supabase.rpc("browse_minified_applications").eq("assembler->>id", '<any_id>'),
```

I get this error 

`
operator does not exist: tp_company->> unknown
`

This could be it but on the other project I have with the exact same code It's working perfectly as it is on the example.
## To Reproduce

Just creating the types and a simple function should work

## Expected behavior

Whenever I make this query it should work and give correct results filtered by the company I'm asking.

## System information

- OS: Windows
- Version of supabase-js: 2.33.1
- Version of Node.js: 19.3.0

## Additional context

Thanks in advance

**Comment by Torres1080** [comment]
I fount out that creating a explicit cast between my type and json solves the problem, but I'm wondering if is there any other less comboluted way of achieving the same effect

```sql
drop function if exists tp_company_to_json(tp_company) cascade;
create or replace function tp_company_to_json(tp_company tp_company)
returns json as
$tp_company_to_json$
  select to_json(C) from company C where C.id = tp_company.id;
$tp_company_to_json$ language sql;

create cast (tp_company as json) with function tp_company_to_json(tp_company) as implicit;
```

**Comment by Torres1080** [comment]
@steve-chavez  I did some debug with my two projects and the queries I found that are being made underhood are the following

![image](https://github.com/supabase/postgrest-js/assets/13919812/9821b053-6caa-44c7-a7b8-743d970ed0e3)

As you can appreciate on the left picture (new project with the bug) there's no such `to_jsonb` call while on the right picture (old project) `to_jsonb` It's being called, don't know why actually.

**Comment by steve-chavez** [comment]
@Torres1080 Can you compare both projects PostgREST versions?

You can get it from the `https://<project_ref>.supabase.co/rest/v1` endpoints. There should be an OpenAPI json output with a version field there.

**Comment by Torres1080** [comment]
@steve-chavez 11.2 (not working) vs 11.1 (working)

![image](https://github.com/supabase/postgrest-js/assets/13919812/88c89923-ed53-4518-ae28-9f87a48ed91e)

**Comment by steve-chavez** [comment]
@Torres1080 Thanks for the report. We're going to fix this on https://github.com/PostgREST/postgrest/issues/2929.

**Comment by Torres1080** [comment]
@steve-chavez You're welcome 👍

**Comment by soedirgo** [comment]
Closing this as it's already fixed in the latest PostgREST release.
