### ISSUE TITLE
aliasing joined tables in .select('*')

### ISSUE THREAD

**Issue by c00** [supabase/postgrest-js#484]
# Improve documentation

There's a super nifty feature: renaming columns / tables in a `select()`, to influence the shape of the resulting object. However, it is not really documented anywhere.

## Link 

[This](https://supabase.com/docs/reference/javascript/select?example=query-the-same-foreign-table-multiple-times) is the only place I've found where renaming is shown, but it's labeled "Querying the same foreign table multiple times". 

## Describe the problem

A vital bit of information is missing. tl;dr: I can do `client.from('books').select('*, author:authors(*)')`. This is super helpful, but is not documented anywhere.

Example tables:

```yaml
books:
  id: number
  title: text
  isbn: text
  author_id: number # FK > author.id

authors:
  id: number
  name: text
```

Now, I want to fetch book id 1, with the author.

```ts
const result = client.from('books').select('*, authors(*)').eq('id', 1).single();
const book = result.data;
console.log(`The book ${book.title} is written by ${book.authors.name}.'`);
```

The fact that the property `book.authors` is named as a plural, but the value is a singular author, is not great. This is a pretty common scenario when joining tables. Luckily we can change that like so:

```ts
const result = client.from('books').select('*, author:authors(*)').eq('id', 1).single();
                                               //^ Here we add an alias for the table
const book = result.data;
console.log(`The book ${book.title} is written by ${book.author.name}.'`);
```

This is much more reasonable. However, documentation of this is missing.

## Describe the improvement

On [this page](https://supabase.com/docs/reference/javascript/select), in the section of fetch examples, add 2 examples. One called "rename columns"  and one called "rename joined tables". The first example would be to showcase renaming normal columns such as `.select('name:title')`. The second example would be specifically about the use-case described above.

## Additional context

In my code, getting more than one table's data at the same time is very common. And renaming columns like this is an essential tool for making the resulting objects easy to use. I would love it to be a lot clearer to new people reading the docs, that this is possible. It would've saved me a lot of refactoring at least :)

**Comment by sim1029** [comment]
@rookledookle Do you have an example of how to alias with a foreign key? Trying to do that right now and can't figure it out

**Comment by vincent-vaur** [comment]
> @rookledookle Do you have an example of how to alias with a foreign key? Trying to do that right now and can't figure it out

You can do it for now like @c00 said:

`const result = client.from('books').select('*, author:authors(*)').eq('id', 1);`

The `alias:join_table` syntax works for me :+1:

**Comment by yang-zhang-work** [comment]
in the example @c00 gave, is there a way to reference the `name` or `id` of the author without having the `author` as the middle layer?

aka, `const result = client.from('books').select('*, authors(*)').eq('id', 1).single();
const book = result.data;` is there a way to structure the query, so that I can alias author name as `author_name` directly instead of having to reference `author.name` or `authors.name`?

Thanks.

**Comment by soedirgo** [comment]
Hi @yang-zhang-work, please post it as a question [here](https://github.com/orgs/supabase/discussions/categories/questions) instead, thanks!
