### ISSUE TITLE
Typescript Support for Aggregate Functions

### ISSUE THREAD

**Issue by ConProgramming** [supabase/postgrest-js#520]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Aggregate functions, just added in #206 are not supported in Typescript.

So for example will get the error ParserError<"Expected identifier at ), label">[].

Would love to see fixed quick like #459 was.

**Comment by bnjmnt4n** [comment]
I can send a PR for this.
