### ISSUE TITLE
Inner Join Types Do Not Work Correctly

### ISSUE THREAD

**Issue by jdgamble555** [supabase/postgrest-js#536]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I made a[ simple repository](https://github.com/jdgamble555/supabase-types/tree/master). You can run `npx supabase start`, but it is not necessary.  Just open the file in VS Code and see the problems.

Here is the [Test Types](https://github.com/jdgamble555/supabase-types/blob/master/src/lib/index.ts)

Here is the [Schema](https://github.com/jdgamble555/supabase-types/blob/master/supabase/migrations/20240520210322_initial.sql)

Or if you want to manually test it:
```sql
CREATE TABLE users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE posts (
    post_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE comments (
    comment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    post_id UUID NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

```

## Expected behavior

I want to do an inner join and get the correct types. 

```js
// DOES NOT WORK, is empty array
const test1 = await supabase.from('posts').select('*, user:user_id(*)')

// DOES NOT WORK, is possibly null
const test2 = await supabase.from('posts').select('*, user:users(*)');

// DOES NOT WORK, is array instead of single
const test3 = await supabase.from('posts').select('*, user:users!user_id(*)');
```
### What I want
```js
const test1: PostgrestSingleResponse<{
    content: string;
    created_at: string;
    post_id: string;
    title: string;
    updated_at: string | null;
    user_id: string;
    user: {
        created_at: string;
        email: string;
        password_hash: string;
        user_id: string;
        username: string;
    };
}[]>
```
### Test 1 Returns
```js
const test1: PostgrestSingleResponse<{
    content: string;
    created_at: string;
    post_id: string;
    title: string;
    updated_at: string | null;
    user_id: string;
    user: {}[];
}[]>
```
### Test 2 Returns
```js
const test2: PostgrestSingleResponse<{
    content: string;
    created_at: string;
    post_id: string;
    title: string;
    updated_at: string | null;
    user_id: string;
    user: {
        created_at: string;
        email: string;
        password_hash: string;
        user_id: string;
        username: string;
    } | null;
}[]>
```
### Test 3 Returns
```js
const test3: PostgrestSingleResponse<{
    content: string;
    created_at: string;
    post_id: string;
    title: string;
    updated_at: string | null;
    user_id: string;
    user: {
        created_at: string;
        email: string;
        password_hash: string;
        user_id: string;
        username: string;
    }[];
}[]>
```

I really just need `test` to return the correct typing. It is clearly a required FK with only one option, so it shouldn't be null nor an array.

## System information
- Supabase-js: 2.43.2
- Supabase: 1.167.4

## Additional context

I have looked at these related posts, but none quite state the same problem clearly:
- https://github.com/supabase/postgrest-js/issues/223
- https://github.com/supabase/postgrest-js/issues/408 - Seems to be related though
- https://github.com/supabase/postgrest-js/issues/303

J

**Comment by zineanteoh** [comment]
facing the same issue, but changing the type of `id` of `users` table from `uuid` to `text` works for me. 

is there a way to have the inner join query work for `uuid`?

**Comment by soedirgo** [comment]
@zineanteoh let me know if that works for you too! We have an example on our docs [here](https://supabase.com/docs/reference/javascript/select) but we might need to make it more front and center.

**Comment by soedirgo** [comment]
👍 thanks for the feedback - this should get better as we get stricter with the typings, e.g. showing a type error instead of falling back to `{}` or `T[]`.

**Comment by jdgamble555** [comment]
@soedirgo - I'm not having that problem. I simplified your schema to:
```sql
CREATE TABLE IF NOT EXISTS "public"."user_projects"(
    "id" "uuid" PRIMARY KEY DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "name" "text",
    "req_hyperparams_map" "json",
    "req_start_date" "date",
    "req_settings" "json",
    "req_model_id" "uuid",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "req_source_id" "uuid"
);

CREATE TABLE IF NOT EXISTS "public"."projects"(
    "id" "uuid" NOT NULL PRIMARY KEY REFERENCES public.user_projects(id),
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "name" "text",
    "hyperparams_map" "json",
    "evaluation_criterias" "json",
    "start_date" "date",
    "last_executed_at" timestamp with time zone,
    "error_message" "text",
    "settings" "json",
    "source_id" "uuid"
);
```
Here is the types you get for:
```ts
await supabase.from('posts').select('*, user:users!inner(*)');
```
```sql
PostgrestSingleResponse<{
    id: string;
    project: {
        created_at: string;
        error_message: string | null;
        evaluation_criterias: Json;
        hyperparams_map: Json;
        id: string;
        last_executed_at: string | null;
        ... 4 more ...;
        updated_at: string | null;
    } | null;
}[]>
```
The reason it is possibly `null` is because `user_projects` don't have an FK that mandates it exists. If you put the FK the other way around, you won't that problem. Either way, I'm not getting an array as an option. 

https://github.com/jdgamble555/supabase-types/blob/master/src/lib/index.ts

J

**Comment by daveycodez** [comment]
Need to address having MULTIPLE references to users. Like a Direct Message which can have user_id AND recipient_id plz
