### ISSUE TITLE
PostgresClient is not a constructor

### ISSUE THREAD

**Issue by RamyaChinnadurai** [supabase/postgrest-js#538]
Starting this morning, I began encountering the error `PostgresClient is not a constructor` despite not making any changes to my code.

I'm currently using `@supabase/supabase-js: 2.12.0`. 

I suspected that the issue might be related to a recent update in one of the dependencies. Turns out `supabase/postgres-js` updated in the last 24 hours

As a temporary workaround, I have forced the use of a previous version of the dependency by adding the following to my package.json:

```js
resolutions: {
 "@supabase/postgrest-js": "1.1.1",
}
```

Looking for a permanent solution for this case

**Comment by KTayy** [comment]
Hi all, I had the same issue, I just used a diff version in my import statement and it worked out. in my case it was 
`import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.43.1'` 

did not change anything else
