### ISSUE TITLE
Release 1.15.6 has broken type generation

### ISSUE THREAD

**Issue by DuncanLHS** [supabase/postgrest-js#545]
# Bug report

Found by upgrading supabase-js from 2.43.5 to 2.43.6.

Return type generation is generally broken in this release, it's widespread but not on everything. Instead of well typed data returns I'm now getting type `any` on many of my supabase postgrest calls.

I haven't managed to find what the differing factor of why it works in some cases but not others yet but on first look it appears to work on some tables on not others rather than it being related to any particular function like .eq() or .filter() etc.

Rolling back to supabase-js 2.43.5 has fixed the issue for now.

**Comment by jperasmus** [comment]
I am experiencing this issue even on v2.43.5

From what I could tell so far, is that when you `select(*)`, the types are inferred as usual, but when you are more specific, `select(id, some_other_field)`, that breaks down.

@DuncanLHS are you seeing the same with specific selects?

**Comment by silentworks** [comment]
@jperasmus that's a different issue and what you are asking about has never worked in this library at all.

**Comment by jperasmus** [comment]
Maybe it isn't an intentional feature, but it definitely has worked before.

![Screenshot 2024-06-27 at 12 47 08](https://github.com/supabase/postgrest-js/assets/6787452/e760d841-04e0-44a7-ae23-7c747d906040)
![Screenshot 2024-06-27 at 12 46 35](https://github.com/supabase/postgrest-js/assets/6787452/d2d155be-f9aa-4ee3-9070-842213042b07)

**Comment by silentworks** [comment]
@jperasmus I think I misunderstood what you were asking. I though you were asking if you would get autocomplete when you type the column names in the `.select` method. What you have stated above is correct, that is how it should work. That is broken for sure and the Supabase team is aware of it. They are working on a fix now.

**Comment by jperasmus** [comment]
Thanks @silentworks I assumed it was probably just a misunderstanding. It looks like the issue is fixed now. I'll test it out.
