### ISSUE TITLE
Unable to import helper types since 1.15.6

### ISSUE THREAD

**Issue by olee** [supabase/postgrest-js#551]
# Bug report

## Describe the bug

Before 1.15.6 it was possible to import helper types from `@supabase/postgrest-js` to perform type mappings etc. like this:
```ts
import type { GetResult } from "@supabase/postgrest-js/dist/module/select-query-parser";

export type TablesSelect<
    Schema extends GenericSchema,
    TableName extends keyof Schema['Tables'],
    Query extends string,
> = GetResult<
    Schema,
    Schema['Tables'][TableName]['Row'],
    TableName,
    Schema['Tables'][TableName] extends { Relationships: infer R } ? R : never,
    Query
>;
```

However, starting from version 1.15.6 with [the change to the package build (package.json etc)](https://github.com/supabase/postgrest-js/commit/2c4e846c8f697f760e15e06a60014e8b93bf3b34#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R19-R22), it became impossible to import any files from subdirectories of the build because of the exports configuration.

## Expected behavior

All types of the library which are publicly exposed as part of generics, function arguments and whatsoever should be properly exported imho so that it is possible to properly type code depending on postgrest-js.

The easiest solution would probably be to export helper types through some namespace from index.ts.

**Comment by soedirgo** [comment]
Hi! These helper types have always been internal and subject to breaking changes - they're not part of the API. Can you share your use case and why you need them?

**Comment by olee** [comment]
The use case is exactly as described above: To generate types for table selects.

For example to write a component that accepts some data which has been selected somewhere else:

```ts
function MyUser(props: { entity: TablesSelect<'users', 'id,first_name,last_name,avatar'> }) {
  return (
    <div>...render user here...</div>
  );
}

// ... at some other location
await supabaseClient.from('users').select('id,first_name,last_name,avatar')....;
```

This is extremly useful and currently prevents us from upgrading supabase client as this is not possible anymore now.

**Comment by tobico** [comment]
I'm also using `GetResult` extensively as the data fetched from my queries is passed around various places in my frontend and I want to correctly type all components and functions that process it.

**Comment by cco3** [comment]
If I understand correctly, there were three way to get result types:

1. Use GetResult, etc.
2. Run the query and get the type of the result
3. Wrap a query in a function and get the return type of the function

1 wasn't supported and was somewhat painful.  2 doesn't give much flexibility for creating helper functions etc. 3 is heavy.

Could we please get a supported way of creating query result types that doesn't require running or wrapping a query?

**Comment by lauri865** [comment]
This is a major breaking change for us, making developer experience much worse. Any kind of higher order abstractions that pass through types become much more difficult to build.

**Comment by lauri865** [comment]
Internal or not, since there's no other good alternative, the community has been forced to use it, as you can see below:
https://github.com/search?q=postgrest-js+%22select-query-parser%22&type=code

**Comment by olee** [comment]
@lauri865 that's some really nice evidence there - didn't know soo many others had to "hack" their way into the lib to find that GetResult type and figure out how to use it etc.
That's why I would really like for there to be a proper, official way of doing this.

**Comment by uncvrd** [comment]
Also would like to +1 this, it makes it extremely easy to be able to type the results from a query. I was inspired by the Supabase Cache Helpers library which uses this method heavily too. Would really appreciate if this was provided externally 🙏

**Comment by soedirgo** [comment]
Thanks all, seems like a proper support is needed here. I'll see if this can be accomplished with the already exported [QueryResult](https://github.com/supabase/supabase-js/blob/96caa1d408d03bd59f38f1c976d5d2b2c64b3161/src/lib/types.ts#L111) or, failing that, we'll reexport GetResult

**Comment by olee** [comment]
That's wonderful news!
The only other option I'd have taken soon would have been completely copying the required types of GetResult into our own codebase which I'd really like to avoid.

**Comment by olee** [comment]
Hey, is there any progress on this or is there anything we could help with?

**Comment by uncvrd** [comment]
Hi all, in an attempt to help move things along I made a simple PR. Let me know if this can be improved :) 

#560

**Comment by alexgorbatchev** [comment]
As an additional +1 here, I also want to mention that [this is used](https://github.com/psteinroe/supabase-cache-helpers/blob/main/packages/postgrest-swr/src/mutate/types.ts) by `supabase-cache-helper` which has a [full video](https://www.youtube.com/watch?v=g2k9-6Ka2QY) on the Supabase YouTube channel

**Comment by olee** [comment]
Hey, sorry to bother you @soedirgo, but think this might be implemented?
I mean we are not talking about any large feature, just about exporting an already existing type (either directly, with an `Unstable_` prefix or through a proper helper) which otherwise blocks quite a few users from upgrading their version of postgrest-js.
I would make a PR, but that wouldn't make sense without a decision on someone from the maintainer side on which solution to opt for yet I think.

**Comment by uncvrd** [comment]
Yea this is holding me up on upgrading as well, we have as PR #560 at your convenience
