### ISSUE TITLE
Add a retry in case of 520 Cloudflare status

### ISSUE THREAD

**Issue by steve-chavez** [supabase/postgrest-js#587]
## Problem

Sometimes network error can happen due to Cloudflare network errors.

## Proposal

Add retries whenever 520 status occur.

## Notes

- This was previously tried on https://github.com/supabase/postgrest-js/pull/267/
- There's also a gist here https://gist.github.com/thebengeu/8f564dbd7dfe660dda325fdfa1d06042

**Comment by soedirgo** [comment]
Adding a docs page on how to do retries is preferred here, there are too many variables in retry behavior (when to retry/which status codes, which retry algorithm to use) for us to be able to expose it as a stable interface.

**Comment by steve-chavez** [comment]
Ok, let's not do this now.
