### ISSUE TITLE
Delete should not be done if there are no filters applied

### ISSUE THREAD

**Issue by dragarcia** [supabase/postgrest-js#6]
At the moment, just doing a .delete() will delete everything in the table. This could lead to accidental deletion of all content in a table.
- What could be done would be to restrict delete to only work if any of the filters are present.

**Comment by kiwicopple** [comment]
@dragarcia can you add a test for this one too?

**Comment by dragarcia** [comment]
I have one commit with new tests otw. Will push that up in a while.

**Comment by dragarcia** [comment]
Test for the above and other new tests have been pushed via 03aad8d.
