### ISSUE TITLE
Implement `on_conflict` 

### ISSUE THREAD

**Issue by awalias** [supabase/postgrest-js#78]
Implement `on_conflict` option on inserts

from: [http://postgrest.org/en/latest/api.html#on-conflict](http://postgrest.org/en/latest/api.html#on-conflict)

The user should be able to upsert on UNIQUE columns (that may not be the primary key)

**Comment by kiwicopple** [comment]
@soedirgo is this one still relevant after all your changes? If so, perhaps we label it for Hacktoberfest and see if the community want to contribute?

**Comment by soedirgo** [comment]
👍 Sounds good, `insert` is currently missing this feature. This can be an [option](https://github.com/supabase/postgrest-js/blob/d2f944a347a86f79397ca26876effb39d356241c/src/builder.ts#L122) alongside `upsert` that gets used when `upsert` is `true`.
