### ISSUE TITLE
Abort a request

### ISSUE THREAD

**Issue by Laplo** [supabase/postgrest-js#9]
Hi, I didn't see any docs on how it is possible to abort a request for example when we switch of component and so the request of the first one is not needed anymore.

Did you plan to add something like this or is it already possible?

**Comment by awalias** [comment]
Hi @Laplo , the request object returned from `.select` etc. is just a [https://github.com/visionmedia/superagent](https://github.com/visionmedia/superagent) object, I had a quick glance at their functionality and couldn't see anything relevant but you may want to dig a bit digger.

It may also be possible to handle this in the code that handles the response, perhaps by checking whether the component is still active. If you want to provide a code example we may be able to dig a little deeper

**Comment by kiwicopple** [comment]
Looks like it may be handled in the baseAgent here:
https://github.com/visionmedia/superagent/blob/56ce51728083392132505218c05edd5cf9f60c58/src/request-base.js#L452

And test here: 
https://github.com/visionmedia/superagent/blob/477f3c5141cb0f80e593baf477e4b5a172ac1839/test/basic.js#L581

I imagine you may be able to do something like:

```js
let req = await client
    .from('countries')
    .select('*')

// ...
req.abort()
```

I'm yet to test, but perhaps you can try that out @Laplo and then let us know? I'll add a test for it at some point

**Comment by Laplo** [comment]
Great I’ll try it out and let you know !

**Comment by Laplo** [comment]
It works like that (example in React) :
`const loadUsers = () => {
        request = client
            .from('address_data')
            .select('*')
        request.then(resolve => {
           console.log(resolve);
        });
    };

    useEffect(() =>{
        return () => {
            console.log(request);
            request.abort();
        };
    }, []);`

Thanks for your help !
